# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_nfs/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanNfs
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_nfs,
      attributes_class: Digitalocean::Types::NfsAttributes,
      outputs: { id: :id },
      map: [:name, :region, :size, :vpc_id],
      map_present: [:performance_tier, :tags]
  end
  module Digitalocean
    include DigitaloceanNfs
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
