# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_gradientai_knowledge_base/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanGradientaiKnowledgeBase
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_gradientai_knowledge_base,
      attributes_class: Digitalocean::Types::GradientaiKnowledgeBaseAttributes,
      outputs: { id: :id },
      map: [:datasources, :embedding_model_uuid, :name, :project_id, :region],
      map_present: [:added_to_agent_at, :database_id, :last_indexing_job, :tags, :vpc_uuid],
      map_bool: [:is_public]
  end
  module Digitalocean
    include DigitaloceanGradientaiKnowledgeBase
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
