# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class GradientaiKnowledgeBaseAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :datasources, T::Array.of(T::Hash)
    attribute :embedding_model_uuid, T::String
    attribute :name, T::String
    attribute :project_id, T::String
    attribute :region, T::String
    attribute? :added_to_agent_at, T::String.optional
    attribute? :database_id, T::String.optional
    attribute? :is_public, T::Bool.optional
    attribute? :last_indexing_job, T::Array.of(T::Hash).optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :vpc_uuid, T::String.optional
  end
end
