# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_container_registry/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanContainerRegistry
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_container_registry,
      attributes_class: Digitalocean::Types::ContainerRegistryAttributes,
      outputs: { id: :id },
      map: [:name, :subscription_tier_slug]
  end
  module Digitalocean
    include DigitaloceanContainerRegistry
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
