# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseClusterAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :engine, T::String
    attribute :name, T::String
    attribute :node_count, T::Float
    attribute :region, T::String
    attribute :size, T::String
    attribute? :backup_restore, T::Array.of(T::Hash).optional
    attribute? :eviction_policy, T::String.optional
    attribute? :maintenance_window, T::Array.of(T::Hash).optional
    attribute? :sql_mode, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :version, T::String.optional
  end
end
