# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_spaces_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanSpacesKey
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_spaces_key,
      attributes_class: Digitalocean::Types::SpacesKeyAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:grant]
  end
  module Digitalocean
    include DigitaloceanSpacesKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
