# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_volume/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanVolume
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_volume,
      attributes_class: Digitalocean::Types::VolumeAttributes,
      outputs: { id: :id },
      map: [:name, :region, :size],
      map_present: [:description, :initial_filesystem_label, :initial_filesystem_type, :snapshot_id, :tags]
  end
  module Digitalocean
    include DigitaloceanVolume
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
