# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class VolumeAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute :region, T::String
    attribute :size, T::Float
    attribute? :description, T::String.optional
    attribute? :initial_filesystem_label, T::String.optional
    attribute? :initial_filesystem_type, T::String.optional
    attribute? :snapshot_id, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
