# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_database_online_migration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDatabaseOnlineMigration
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_database_online_migration,
      attributes_class: Digitalocean::Types::DatabaseOnlineMigrationAttributes,
      outputs: { id: :id },
      map: [:cluster_id, :source],
      map_present: [:ignore_dbs],
      map_bool: [:disable_ssl]
  end
  module Digitalocean
    include DigitaloceanDatabaseOnlineMigration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
