# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseOnlineMigrationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute :source, T::Array.of(T::Hash)
    attribute? :disable_ssl, T::Bool.optional
    attribute? :ignore_dbs, T::Array.of(T::String).optional
  end
end
