# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_gradientai_agent_knowledge_base_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanGradientaiAgentKnowledgeBaseAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_gradientai_agent_knowledge_base_attachment,
      attributes_class: Digitalocean::Types::GradientaiAgentKnowledgeBaseAttachmentAttributes,
      outputs: { id: :id },
      map: [:agent_uuid, :knowledge_base_uuid]
  end
  module Digitalocean
    include DigitaloceanGradientaiAgentKnowledgeBaseAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
