# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_volume_snapshot/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanVolumeSnapshot
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_volume_snapshot,
      attributes_class: Digitalocean::Types::VolumeSnapshotAttributes,
      outputs: { id: :id },
      map: [:name, :volume_id],
      map_present: [:tags]
  end
  module Digitalocean
    include DigitaloceanVolumeSnapshot
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
