# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class UptimeAlertAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :check_id, T::String
    attribute :name, T::String
    attribute :notifications, T::Array.of(T::Hash)
    attribute :type, T::String
    attribute? :comparison, T::String.optional
    attribute? :period, T::String.optional
    attribute? :threshold, T::Float.optional
  end
end
