# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_reserved_ipv6/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanReservedIpv6
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_reserved_ipv6,
      attributes_class: Digitalocean::Types::ReservedIpv6Attributes,
      outputs: { id: :id },
      map: [:region_slug]
  end
  module Digitalocean
    include DigitaloceanReservedIpv6
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
