# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_reserved_ip_assignment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanReservedIpAssignment
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_reserved_ip_assignment,
      attributes_class: Digitalocean::Types::ReservedIpAssignmentAttributes,
      outputs: { id: :id },
      map: [:droplet_id, :ip_address]
  end
  module Digitalocean
    include DigitaloceanReservedIpAssignment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
