# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class RecordAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :domain, T::String
    attribute :name, T::String
    attribute :type, T::String
    attribute :value, T::String
    attribute? :flags, T::Float.optional
    attribute? :port, T::Float.optional
    attribute? :priority, T::Float.optional
    attribute? :tag, T::String.optional
    attribute? :weight, T::Float.optional
  end
end
