# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_vpc/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanVpc
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_vpc,
      attributes_class: Digitalocean::Types::VpcAttributes,
      outputs: { id: :id },
      map: [:name, :region],
      map_present: [:description]
  end
  module Digitalocean
    include DigitaloceanVpc
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
