# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_spaces_bucket_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanSpacesBucketPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_spaces_bucket_policy,
      attributes_class: Digitalocean::Types::SpacesBucketPolicyAttributes,
      outputs: { id: :id },
      map: [:bucket, :policy, :region]
  end
  module Digitalocean
    include DigitaloceanSpacesBucketPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
