# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_custom_image/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanCustomImage
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_custom_image,
      attributes_class: Digitalocean::Types::CustomImageAttributes,
      outputs: { id: :id },
      map: [:name, :regions, :url],
      map_present: [:description, :distribution, :tags]
  end
  module Digitalocean
    include DigitaloceanCustomImage
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
