# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class KubernetesNodePoolAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute :name, T::String
    attribute :size, T::String
    attribute? :auto_scale, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :max_nodes, T::Float.optional
    attribute? :min_nodes, T::Float.optional
    attribute? :node_count, T::Float.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :taint, T::Array.of(T::Hash).optional
  end
end
