# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_spaces_bucket/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanSpacesBucket
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_spaces_bucket,
      attributes_class: Digitalocean::Types::SpacesBucketAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :cors_rule, :lifecycle_rule, :region, :versioning],
      map_bool: [:force_destroy]
  end
  module Digitalocean
    include DigitaloceanSpacesBucket
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
