# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class SpacesBucketAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute? :acl, T::String.optional
    attribute? :cors_rule, T::Array.of(T::Hash).optional
    attribute? :force_destroy, T::Bool.optional
    attribute? :lifecycle_rule, T::Array.of(T::Hash).optional
    attribute? :region, T::String.optional
    attribute? :versioning, T::Array.of(T::Hash).optional
  end
end
