# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_database_postgresql_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDatabasePostgresqlConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_database_postgresql_config,
      attributes_class: Digitalocean::Types::DatabasePostgresqlConfigAttributes,
      outputs: { id: :id },
      map: [:cluster_id],
      map_present: [:pgbouncer, :timescaledb]
  end
  module Digitalocean
    include DigitaloceanDatabasePostgresqlConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
