# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabasePostgresqlConfigAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute? :pgbouncer, T::Array.of(T::Hash).optional
    attribute? :timescaledb, T::Array.of(T::Hash).optional
  end
end
