# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class ContainerRegistryDockerCredentialsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :registry_name, T::String
    attribute? :expiry_seconds, T::Float.optional
    attribute? :write, T::Bool.optional
  end
end
