# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_uptime_check/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanUptimeCheck
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_uptime_check,
      attributes_class: Digitalocean::Types::UptimeCheckAttributes,
      outputs: { id: :id },
      map: [:name, :target],
      map_present: [:regions, :type],
      map_bool: [:enabled]
  end
  module Digitalocean
    include DigitaloceanUptimeCheck
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
