# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class UptimeCheckAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute :target, T::String
    attribute? :enabled, T::Bool.optional
    attribute? :regions, T::Array.of(T::String).optional
    attribute? :type, T::String.optional
  end
end
