# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_loadbalancer/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanLoadbalancer
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_loadbalancer,
      attributes_class: Digitalocean::Types::LoadbalancerAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:algorithm, :domains, :droplet_tag, :firewall, :forwarding_rule, :glb_settings, :healthcheck, :network, :network_stack, :region, :size, :sticky_sessions, :tls_cipher_policy],
      map_bool: [:disable_lets_encrypt_dns_records, :enable_backend_keepalive, :enable_proxy_protocol, :redirect_http_to_https]
  end
  module Digitalocean
    include DigitaloceanLoadbalancer
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
