# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class LoadbalancerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute? :algorithm, T::String.optional
    attribute? :disable_lets_encrypt_dns_records, T::Bool.optional
    attribute? :domains, T::Array.of(T::Hash).optional
    attribute? :droplet_tag, T::String.optional
    attribute? :enable_backend_keepalive, T::Bool.optional
    attribute? :enable_proxy_protocol, T::Bool.optional
    attribute? :firewall, T::Array.of(T::Hash).optional
    attribute? :forwarding_rule, T::Array.of(T::Hash).optional
    attribute? :glb_settings, T::Array.of(T::Hash).optional
    attribute? :healthcheck, T::Array.of(T::Hash).optional
    attribute? :network, T::String.optional
    attribute? :network_stack, T::String.optional
    attribute? :redirect_http_to_https, T::Bool.optional
    attribute? :region, T::String.optional
    attribute? :size, T::String.optional
    attribute? :sticky_sessions, T::Array.of(T::Hash).optional
    attribute? :tls_cipher_policy, T::String.optional
  end
end
