# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_gradientai_agent_route/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanGradientaiAgentRoute
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_gradientai_agent_route,
      attributes_class: Digitalocean::Types::GradientaiAgentRouteAttributes,
      outputs: { id: :id },
      map: [:child_agent_uuid, :parent_agent_uuid],
      map_present: [:if_case, :route_name],
      map_bool: [:rollback]
  end
  module Digitalocean
    include DigitaloceanGradientaiAgentRoute
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
