# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_database_connection_pool/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDatabaseConnectionPool
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_database_connection_pool,
      attributes_class: Digitalocean::Types::DatabaseConnectionPoolAttributes,
      outputs: { id: :id },
      map: [:cluster_id, :db_name, :mode, :name, :size],
      map_present: [:user]
  end
  module Digitalocean
    include DigitaloceanDatabaseConnectionPool
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
