# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseConnectionPoolAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute :db_name, T::String
    attribute :mode, T::String
    attribute :name, T::String
    attribute :size, T::Float
    attribute? :user, T::String.optional
  end
end
