# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_byoip_prefix/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanByoipPrefix
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_byoip_prefix,
      attributes_class: Digitalocean::Types::ByoipPrefixAttributes,
      outputs: { id: :id },
      map: [:prefix, :region],
      map_present: [:signature],
      map_bool: [:advertised]
  end
  module Digitalocean
    include DigitaloceanByoipPrefix
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
