# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class ByoipPrefixAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :prefix, T::String
    attribute :region, T::String
    attribute? :advertised, T::Bool.optional
    attribute? :signature, T::String.optional
  end
end
