# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_database_kafka_schema_registry/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDatabaseKafkaSchemaRegistry
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_database_kafka_schema_registry,
      attributes_class: Digitalocean::Types::DatabaseKafkaSchemaRegistryAttributes,
      outputs: { id: :id },
      map: [:cluster_id, :schema, :schema_type, :subject_name]
  end
  module Digitalocean
    include DigitaloceanDatabaseKafkaSchemaRegistry
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
