# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_database_kafka_topic/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDatabaseKafkaTopic
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_database_kafka_topic,
      attributes_class: Digitalocean::Types::DatabaseKafkaTopicAttributes,
      outputs: { id: :id },
      map: [:cluster_id, :name],
      map_present: [:config, :partition_count, :replication_factor]
  end
  module Digitalocean
    include DigitaloceanDatabaseKafkaTopic
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
