# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseKafkaTopicAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute :name, T::String
    attribute? :config, T::Array.of(T::Hash).optional
    attribute? :partition_count, T::Float.optional
    attribute? :replication_factor, T::Float.optional
  end
end
