# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_kubernetes_cluster/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanKubernetesCluster
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_kubernetes_cluster,
      attributes_class: Digitalocean::Types::KubernetesClusterAttributes,
      outputs: { id: :id },
      map: [:name, :node_pool, :region, :version],
      map_present: [:amd_gpu_device_metrics_exporter_plugin, :amd_gpu_device_plugin, :cluster_autoscaler_configuration, :control_plane_firewall, :kubeconfig_expire_seconds, :maintenance_policy, :nvidia_gpu_device_plugin, :rdma_shared_device_plugin, :routing_agent, :sso, :tags],
      map_bool: [:auto_upgrade, :destroy_all_associated_resources, :ha, :registry_integration, :surge_upgrade]
  end
  module Digitalocean
    include DigitaloceanKubernetesCluster
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
