# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class KubernetesClusterAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute :node_pool, T::Array.of(T::Hash)
    attribute :region, T::String
    attribute :version, T::String
    attribute? :amd_gpu_device_metrics_exporter_plugin, T::Array.of(T::Hash).optional
    attribute? :amd_gpu_device_plugin, T::Array.of(T::Hash).optional
    attribute? :auto_upgrade, T::Bool.optional
    attribute? :cluster_autoscaler_configuration, T::Array.of(T::Hash).optional
    attribute? :control_plane_firewall, T::Array.of(T::Hash).optional
    attribute? :destroy_all_associated_resources, T::Bool.optional
    attribute? :ha, T::Bool.optional
    attribute? :kubeconfig_expire_seconds, T::Float.optional
    attribute? :maintenance_policy, T::Array.of(T::Hash).optional
    attribute? :nvidia_gpu_device_plugin, T::Array.of(T::Hash).optional
    attribute? :rdma_shared_device_plugin, T::Array.of(T::Hash).optional
    attribute? :registry_integration, T::Bool.optional
    attribute? :routing_agent, T::Array.of(T::Hash).optional
    attribute? :sso, T::Array.of(T::Hash).optional
    attribute? :surge_upgrade, T::Bool.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
