# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_reserved_ip/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanReservedIp
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_reserved_ip,
      attributes_class: Digitalocean::Types::ReservedIpAttributes,
      outputs: { id: :id },
      map: [:region],
      map_present: [:droplet_id]
  end
  module Digitalocean
    include DigitaloceanReservedIp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
