# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_project_resources/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanProjectResources
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_project_resources,
      attributes_class: Digitalocean::Types::ProjectResourcesAttributes,
      outputs: { id: :id },
      map: [:project, :resources]
  end
  module Digitalocean
    include DigitaloceanProjectResources
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
