# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_tag/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanTag
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_tag,
      attributes_class: Digitalocean::Types::TagAttributes,
      outputs: { id: :id },
      map: [:name]
  end
  module Digitalocean
    include DigitaloceanTag
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
