# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_ssh_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanSshKey
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_ssh_key,
      attributes_class: Digitalocean::Types::SshKeyAttributes,
      outputs: { id: :id },
      map: [:name, :public_key]
  end
  module Digitalocean
    include DigitaloceanSshKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
