# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_nfs_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanNfsAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_nfs_attachment,
      attributes_class: Digitalocean::Types::NfsAttachmentAttributes,
      outputs: { id: :id },
      map: [:region, :share_id, :vpc_id]
  end
  module Digitalocean
    include DigitaloceanNfsAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
