# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_domain/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDomain
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_domain,
      attributes_class: Digitalocean::Types::DomainAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:ip_address]
  end
  module Digitalocean
    include DigitaloceanDomain
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
