# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DomainAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute? :ip_address, T::String.optional
  end
end
