# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_project/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanProject
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_project,
      attributes_class: Digitalocean::Types::ProjectAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :environment, :purpose],
      map_bool: [:is_default]
  end
  module Digitalocean
    include DigitaloceanProject
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
