# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class ProjectAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :environment, T::String.optional
    attribute? :is_default, T::Bool.optional
    attribute? :purpose, T::String.optional
  end
end
