# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseUserAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute :name, T::String
    attribute? :mysql_auth_plugin, T::String.optional
    attribute? :settings, T::Array.of(T::Hash).optional
  end
end
