# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_gradientai_function/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanGradientaiFunction
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_gradientai_function,
      attributes_class: Digitalocean::Types::GradientaiFunctionAttributes,
      outputs: { id: :id },
      map: [:agent_id, :description, :faas_namespace, :function_name, :input_schema],
      map_present: [:faas_name, :output_schema]
  end
  module Digitalocean
    include DigitaloceanGradientaiFunction
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
