# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_droplet/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDroplet
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_droplet,
      attributes_class: Digitalocean::Types::DropletAttributes,
      outputs: { id: :id },
      map: [:image, :name, :size],
      map_present: [:backup_policy, :ssh_keys, :tags, :user_data],
      map_bool: [:backups, :droplet_agent, :graceful_shutdown, :ipv6, :monitoring, :resize_disk]
  end
  module Digitalocean
    include DigitaloceanDroplet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
