# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DropletAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :image, T::String
    attribute :name, T::String
    attribute :size, T::String
    attribute? :backup_policy, T::Array.of(T::Hash).optional
    attribute? :backups, T::Bool.optional
    attribute? :droplet_agent, T::Bool.optional
    attribute? :graceful_shutdown, T::Bool.optional
    attribute? :ipv6, T::Bool.optional
    attribute? :monitoring, T::Bool.optional
    attribute? :resize_disk, T::Bool.optional
    attribute? :ssh_keys, T::Array.of(T::String).optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :user_data, T::String.optional
  end
end
