# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_droplet_snapshot/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDropletSnapshot
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_droplet_snapshot,
      attributes_class: Digitalocean::Types::DropletSnapshotAttributes,
      outputs: { id: :id },
      map: [:droplet_id, :name]
  end
  module Digitalocean
    include DigitaloceanDropletSnapshot
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
