# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_cdn/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanCdn
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_cdn,
      attributes_class: Digitalocean::Types::CdnAttributes,
      outputs: { id: :id },
      map: [:origin],
      map_present: [:custom_domain]
  end
  module Digitalocean
    include DigitaloceanCdn
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
