# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class GradientaiKnowledgeBaseDataSourceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :knowledge_base_uuid, T::String
    attribute? :spaces_data_source, T::Array.of(T::Hash).optional
    attribute? :web_crawler_data_source, T::Array.of(T::Hash).optional
  end
end
