# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_database_valkey_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDatabaseValkeyConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_database_valkey_config,
      attributes_class: Digitalocean::Types::DatabaseValkeyConfigAttributes,
      outputs: { id: :id },
      map: [:cluster_id]
  end
  module Digitalocean
    include DigitaloceanDatabaseValkeyConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
