# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_spaces_bucket_cors_configuration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanSpacesBucketCorsConfiguration
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_spaces_bucket_cors_configuration,
      attributes_class: Digitalocean::Types::SpacesBucketCorsConfigurationAttributes,
      outputs: { id: :id },
      map: [:bucket, :cors_rule, :region]
  end
  module Digitalocean
    include DigitaloceanSpacesBucketCorsConfiguration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
