# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class SpacesBucketCorsConfigurationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :bucket, T::String
    attribute :cors_rule, T::Array.of(T::Hash)
    attribute :region, T::String
  end
end
