# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseOpensearchConfigAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute? :reindex_remote_whitelist, T::Array.of(T::String).optional
  end
end
