# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_partner_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanPartnerAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_partner_attachment,
      attributes_class: Digitalocean::Types::PartnerAttachmentAttributes,
      outputs: { id: :id },
      map: [:connection_bandwidth_in_mbps, :naas_provider, :name, :region, :vpc_ids],
      map_present: [:bgp, :parent_uuid]
  end
  module Digitalocean
    include DigitaloceanPartnerAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
