# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class PartnerAttachmentAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :connection_bandwidth_in_mbps, T::Float
    attribute :naas_provider, T::String
    attribute :name, T::String
    attribute :region, T::String
    attribute :vpc_ids, T::Array.of(T::String)
    attribute? :bgp, T::Array.of(T::Hash).optional
    attribute? :parent_uuid, T::String.optional
  end
end
