# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_gradientai_openai_api_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanGradientaiOpenaiApiKey
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_gradientai_openai_api_key,
      attributes_class: Digitalocean::Types::GradientaiOpenaiApiKeyAttributes,
      outputs: { id: :id },
      map: [:api_key, :name],
      map_present: [:model]
  end
  module Digitalocean
    include DigitaloceanGradientaiOpenaiApiKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
