# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_vpc_peering/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanVpcPeering
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_vpc_peering,
      attributes_class: Digitalocean::Types::VpcPeeringAttributes,
      outputs: { id: :id },
      map: [:name, :vpc_ids]
  end
  module Digitalocean
    include DigitaloceanVpcPeering
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
