# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_app/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanApp
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_app,
      attributes_class: Digitalocean::Types::AppAttributes,
      outputs: { id: :id },
      map_present: [:dedicated_ips, :deployment_per_page, :spec]
  end
  module Digitalocean
    include DigitaloceanApp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
