# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class AppAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute? :dedicated_ips, T::Array.of(T::Hash).optional
    attribute? :deployment_per_page, T::Float.optional
    attribute? :spec, T::Array.of(T::Hash).optional
  end
end
