# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_certificate/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanCertificate
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_certificate,
      attributes_class: Digitalocean::Types::CertificateAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:certificate_chain, :domains, :leaf_certificate, :private_key, :type]
  end
  module Digitalocean
    include DigitaloceanCertificate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
