# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class CertificateAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute? :certificate_chain, T::String.optional
    attribute? :domains, T::Array.of(T::String).optional
    attribute? :leaf_certificate, T::String.optional
    attribute? :private_key, T::String.optional
    attribute? :type, T::String.optional
  end
end
