# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_spaces_bucket_object/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanSpacesBucketObject
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_spaces_bucket_object,
      attributes_class: Digitalocean::Types::SpacesBucketObjectAttributes,
      outputs: { id: :id },
      map: [:bucket, :key, :region],
      map_present: [:acl, :cache_control, :content, :content_base64, :content_disposition, :content_encoding, :content_language, :metadata, :source, :website_redirect],
      map_bool: [:force_destroy]
  end
  module Digitalocean
    include DigitaloceanSpacesBucketObject
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
