# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class SpacesBucketObjectAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :bucket, T::String
    attribute :key, T::String
    attribute :region, T::String
    attribute? :acl, T::String.optional
    attribute? :cache_control, T::String.optional
    attribute? :content, T::String.optional
    attribute? :content_base64, T::String.optional
    attribute? :content_disposition, T::String.optional
    attribute? :content_encoding, T::String.optional
    attribute? :content_language, T::String.optional
    attribute? :force_destroy, T::Bool.optional
    attribute? :metadata, T::Hash.optional
    attribute? :source, T::String.optional
    attribute? :website_redirect, T::String.optional
  end
end
