# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_database_logsink_opensearch/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDatabaseLogsinkOpensearch
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_database_logsink_opensearch,
      attributes_class: Digitalocean::Types::DatabaseLogsinkOpensearchAttributes,
      outputs: { id: :id },
      map: [:cluster_id, :endpoint, :index_prefix, :name],
      map_present: [:ca_cert, :index_days_max, :timeout_seconds]
  end
  module Digitalocean
    include DigitaloceanDatabaseLogsinkOpensearch
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
