# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseLogsinkOpensearchAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute :endpoint, T::String
    attribute :index_prefix, T::String
    attribute :name, T::String
    attribute? :ca_cert, T::String.optional
    attribute? :index_days_max, T::Float.optional
    attribute? :timeout_seconds, T::Float.optional
  end
end
