# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class MonitorAlertAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :alerts, T::Array.of(T::Hash)
    attribute :compare, T::String
    attribute :description, T::String
    attribute :type, T::String
    attribute :value, T::Float
    attribute :window, T::String
    attribute? :enabled, T::Bool.optional
    attribute? :entities, T::Array.of(T::String).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
