# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_gradientai_agent/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanGradientaiAgent
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_gradientai_agent,
      attributes_class: Digitalocean::Types::GradientaiAgentAttributes,
      outputs: { id: :id },
      map: [:instruction, :model_uuid, :name, :project_id, :region],
      map_present: [:agent_guardrail, :anthropic_api_key, :anthropic_key_uuid, :api_key_infos, :api_keys, :chatbot, :chatbot_identifiers, :child_agents, :created_at, :deployment, :description, :functions, :if_case, :k, :knowledge_base_uuid, :knowledge_bases, :max_tokens, :model, :open_ai_api_key, :open_ai_key_uuid, :parent_agents, :retrieval_method, :route_created_by, :route_name, :route_uuid, :tags, :temperature, :template, :top_p, :url, :user_id, :workspace_uuid],
      map_bool: [:provide_citations]
  end
  module Digitalocean
    include DigitaloceanGradientaiAgent
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
