# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseReplicaAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute :name, T::String
    attribute? :region, T::String.optional
    attribute? :size, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
