# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_database_logsink_rsyslog/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanDatabaseLogsinkRsyslog
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_database_logsink_rsyslog,
      attributes_class: Digitalocean::Types::DatabaseLogsinkRsyslogAttributes,
      outputs: { id: :id },
      map: [:cluster_id, :name, :port, :server],
      map_present: [:ca_cert, :client_cert, :client_key, :format, :logline, :structured_data],
      map_bool: [:tls]
  end
  module Digitalocean
    include DigitaloceanDatabaseLogsinkRsyslog
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
