# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class DatabaseLogsinkRsyslogAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :cluster_id, T::String
    attribute :name, T::String
    attribute :port, T::Float
    attribute :server, T::String
    attribute? :ca_cert, T::String.optional
    attribute? :client_cert, T::String.optional
    attribute? :client_key, T::String.optional
    attribute? :format, T::String.optional
    attribute? :logline, T::String.optional
    attribute? :structured_data, T::String.optional
    attribute? :tls, T::Bool.optional
  end
end
