# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_spaces_bucket_logging/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanSpacesBucketLogging
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_spaces_bucket_logging,
      attributes_class: Digitalocean::Types::SpacesBucketLoggingAttributes,
      outputs: { id: :id },
      map: [:bucket, :region, :target_bucket, :target_prefix]
  end
  module Digitalocean
    include DigitaloceanSpacesBucketLogging
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
