# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class SpacesBucketLoggingAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :bucket, T::String
    attribute :region, T::String
    attribute :target_bucket, T::String
    attribute :target_prefix, T::String
  end
end
