# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_nfs_snapshot/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanNfsSnapshot
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_nfs_snapshot,
      attributes_class: Digitalocean::Types::NfsSnapshotAttributes,
      outputs: { id: :id },
      map: [:name, :region, :share_id]
  end
  module Digitalocean
    include DigitaloceanNfsSnapshot
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
