# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/digitalocean_firewall/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DigitaloceanFirewall
    include Pangea::Resources::ResourceBuilder

    define_resource :digitalocean_firewall,
      attributes_class: Digitalocean::Types::FirewallAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:droplet_ids, :inbound_rule, :outbound_rule, :tags]
  end
  module Digitalocean
    include DigitaloceanFirewall
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Digitalocean)
