# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Digitalocean::Types
  include Dry.Types()

  class VpcNatGatewayAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Digitalocean::Types

    attribute :name, T::String
    attribute :region, T::String
    attribute :size, T::Float
    attribute :type, T::String
    attribute :vpcs, T::Array.of(T::Hash)
  end
end
