# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_connection_pool resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabaseConnectionPool do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value', db_name: 'test-value', mode: 'test-value', name: 'test-value', size: 3.14 } }

  describe ':digitalocean_database_connection_pool' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_connection_pool('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_connection_pool', 'test')
        validate_required_attributes(config, [:cluster_id, :db_name, :mode, :name, :size])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_connection_pool('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_connection_pool)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_connection_pool('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_connection_pool.test.id}")
        expect(ref.host).to eq("${digitalocean_database_connection_pool.test.host}")
        expect(ref.password).to eq("${digitalocean_database_connection_pool.test.password}")
        expect(ref.port).to eq("${digitalocean_database_connection_pool.test.port}")
        expect(ref.private_host).to eq("${digitalocean_database_connection_pool.test.private_host}")
        expect(ref.private_uri).to eq("${digitalocean_database_connection_pool.test.private_uri}")
        expect(ref.uri).to eq("${digitalocean_database_connection_pool.test.uri}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_connection_pool('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_connection_pool', 'test')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('password')
        expect(config).not_to have_key('port')
        expect(config).not_to have_key('private_host')
        expect(config).not_to have_key('private_uri')
        expect(config).not_to have_key('uri')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ user: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_connection_pool('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_connection_pool', 'full')
        expect(config).to have_key('user')
      end
    end

    context 'optional attributes' do
      it 'includes user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_connection_pool('opt', required_attrs.merge(user: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_connection_pool', 'opt')
        expect(config).to have_key('user')
      end

      it 'omits user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_connection_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_connection_pool', 'minimal')
        expect(config).not_to have_key('user')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password, :private_uri, :uri]
        expect(sensitive_fields).to include(:password)
        expect(sensitive_fields).to include(:private_uri)
        expect(sensitive_fields).to include(:uri)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_connection_pool('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_connection_pool', 'typed')
        expect(config['cluster_id']).to be_a(String)
        expect(config['db_name']).to be_a(String)
        expect(config['mode']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['size']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_connection_pool('first', required_attrs)
        synth.digitalocean_database_connection_pool('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_connection_pool')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_connection_pool,
    method: :digitalocean_database_connection_pool,
    required_attrs: { cluster_id: 'test-value', db_name: 'test-value', mode: 'test-value', name: 'test-value', size: 3.14 },
    expected_outputs: [:id, :host, :password, :port, :private_host, :private_uri, :uri],
    sensitive_fields: [:password, :private_uri, :uri],
    immutable_fields: [],
    boolean_fields: []
end
