# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_logsink_rsyslog resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabaseLogsinkRsyslog do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value', name: 'test-value', port: 3.14, server: 'test-value' } }

  describe ':digitalocean_database_logsink_rsyslog' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'test')
        validate_required_attributes(config, [:cluster_id, :name, :port, :server])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_logsink_rsyslog('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_logsink_rsyslog)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_logsink_rsyslog('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_logsink_rsyslog.test.id}")
        expect(ref.logsink_id).to eq("${digitalocean_database_logsink_rsyslog.test.logsink_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'test')
        expect(config).not_to have_key('logsink_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ca_cert: 'test-value', client_cert: 'test-value', client_key: 'test-value', format: 'test-value', logline: 'test-value', structured_data: 'test-value', tls: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'full')
        expect(config).to have_key('ca_cert')
        expect(config).to have_key('client_cert')
        expect(config).to have_key('client_key')
        expect(config).to have_key('format')
        expect(config).to have_key('logline')
        expect(config).to have_key('structured_data')
        expect(config).to have_key('tls')
      end
    end

    context 'optional attributes' do
      it 'includes ca_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('opt', required_attrs.merge(ca_cert: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'opt')
        expect(config).to have_key('ca_cert')
      end

      it 'omits ca_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'minimal')
        expect(config).not_to have_key('ca_cert')
      end
      it 'includes client_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('opt', required_attrs.merge(client_cert: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'opt')
        expect(config).to have_key('client_cert')
      end

      it 'omits client_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'minimal')
        expect(config).not_to have_key('client_cert')
      end
      it 'includes client_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('opt', required_attrs.merge(client_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'opt')
        expect(config).to have_key('client_key')
      end

      it 'omits client_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'minimal')
        expect(config).not_to have_key('client_key')
      end
      it 'includes format when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('opt', required_attrs.merge(format: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'opt')
        expect(config).to have_key('format')
      end

      it 'omits format when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'minimal')
        expect(config).not_to have_key('format')
      end
      it 'includes logline when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('opt', required_attrs.merge(logline: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'opt')
        expect(config).to have_key('logline')
      end

      it 'omits logline when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'minimal')
        expect(config).not_to have_key('logline')
      end
      it 'includes structured_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('opt', required_attrs.merge(structured_data: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'opt')
        expect(config).to have_key('structured_data')
      end

      it 'omits structured_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'minimal')
        expect(config).not_to have_key('structured_data')
      end
      it 'includes tls when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('opt', required_attrs.merge(tls: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'opt')
        expect(config).to have_key('tls')
      end

      it 'omits tls when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'minimal')
        expect(config).not_to have_key('tls')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:ca_cert, :client_key]
        expect(sensitive_fields).to include(:ca_cert)
        expect(sensitive_fields).to include(:client_key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts tls=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(tls: val)
          synth.digitalocean_database_logsink_rsyslog("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', "bool_#{val}")
          expect(config['tls']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_logsink_rsyslog', 'typed')
        expect(config['cluster_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['port']).to be_a(Float)
        expect(config['server']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_rsyslog('first', required_attrs)
        synth.digitalocean_database_logsink_rsyslog('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_logsink_rsyslog')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_logsink_rsyslog,
    method: :digitalocean_database_logsink_rsyslog,
    required_attrs: { cluster_id: 'test-value', name: 'test-value', port: 3.14, server: 'test-value' },
    expected_outputs: [:id, :logsink_id],
    sensitive_fields: [:ca_cert, :client_key],
    immutable_fields: [],
    boolean_fields: [:tls]
end
