# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_container_registry resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanContainerRegistry do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', subscription_tier_slug: 'test-value' } }

  describe ':digitalocean_container_registry' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_container_registry', 'test')
        validate_required_attributes(config, [:name, :subscription_tier_slug])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_container_registry('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_container_registry)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_container_registry('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_container_registry.test.id}")
        expect(ref.created_at).to eq("${digitalocean_container_registry.test.created_at}")
        expect(ref.endpoint).to eq("${digitalocean_container_registry.test.endpoint}")
        expect(ref.region).to eq("${digitalocean_container_registry.test.region}")
        expect(ref.server_url).to eq("${digitalocean_container_registry.test.server_url}")
        expect(ref.storage_usage_bytes).to eq("${digitalocean_container_registry.test.storage_usage_bytes}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_container_registry', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('endpoint')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('server_url')
        expect(config).not_to have_key('storage_usage_bytes')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_container_registry', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['subscription_tier_slug']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry('first', required_attrs)
        synth.digitalocean_container_registry('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_container_registry')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_container_registry,
    method: :digitalocean_container_registry,
    required_attrs: { name: 'test-value', subscription_tier_slug: 'test-value' },
    expected_outputs: [:id, :created_at, :endpoint, :region, :server_url, :storage_usage_bytes],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
