# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_gradientai_agent resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanGradientaiAgent do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { instruction: 'test-value', model_uuid: 'test-value', name: 'test-value', project_id: 'test-value', region: 'test-value' } }

  describe ':digitalocean_gradientai_agent' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'test')
        validate_required_attributes(config, [:instruction, :model_uuid, :name, :project_id, :region])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_agent('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_gradientai_agent)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_agent('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_gradientai_agent.test.id}")
        expect(ref.route_created_at).to eq("${digitalocean_gradientai_agent.test.route_created_at}")
        expect(ref.updated_at).to eq("${digitalocean_gradientai_agent.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'test')
        expect(config).not_to have_key('route_created_at')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ agent_guardrail: [{ 'key1' => 'val1' }], anthropic_api_key: [{ 'key1' => 'val1' }], anthropic_key_uuid: 'test-value', api_key_infos: [{ 'key1' => 'val1' }], api_keys: [{ 'key1' => 'val1' }], chatbot: [{ 'key1' => 'val1' }], chatbot_identifiers: [{ 'key1' => 'val1' }], child_agents: [{ 'key1' => 'val1' }], created_at: 'test-value', deployment: [{ 'key1' => 'val1' }], description: 'test-value', functions: [{ 'key1' => 'val1' }], if_case: 'test-value', k: 3.14, knowledge_base_uuid: ['test-value'], knowledge_bases: [{ 'key1' => 'val1' }], max_tokens: 3.14, model: [{ 'key1' => 'val1' }], open_ai_api_key: [{ 'key1' => 'val1' }], open_ai_key_uuid: 'test-value', parent_agents: [{ 'key1' => 'val1' }], provide_citations: true, retrieval_method: 'test-value', route_created_by: 'test-value', route_name: 'test-value', route_uuid: 'test-value', tags: ['test-value'], temperature: 3.14, template: [{ 'key1' => 'val1' }], top_p: 3.14, url: 'test-value', user_id: 'test-value', workspace_uuid: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'full')
        expect(config).to have_key('agent_guardrail')
        expect(config).to have_key('anthropic_api_key')
        expect(config).to have_key('anthropic_key_uuid')
        expect(config).to have_key('api_key_infos')
        expect(config).to have_key('api_keys')
        expect(config).to have_key('chatbot')
        expect(config).to have_key('chatbot_identifiers')
        expect(config).to have_key('child_agents')
        expect(config).to have_key('created_at')
        expect(config).to have_key('deployment')
        expect(config).to have_key('description')
        expect(config).to have_key('functions')
        expect(config).to have_key('if_case')
        expect(config).to have_key('k')
        expect(config).to have_key('knowledge_base_uuid')
        expect(config).to have_key('knowledge_bases')
        expect(config).to have_key('max_tokens')
        expect(config).to have_key('model')
        expect(config).to have_key('open_ai_api_key')
        expect(config).to have_key('open_ai_key_uuid')
        expect(config).to have_key('parent_agents')
        expect(config).to have_key('provide_citations')
        expect(config).to have_key('retrieval_method')
        expect(config).to have_key('route_created_by')
        expect(config).to have_key('route_name')
        expect(config).to have_key('route_uuid')
        expect(config).to have_key('tags')
        expect(config).to have_key('temperature')
        expect(config).to have_key('template')
        expect(config).to have_key('top_p')
        expect(config).to have_key('url')
        expect(config).to have_key('user_id')
        expect(config).to have_key('workspace_uuid')
      end
    end

    context 'optional attributes' do
      it 'includes agent_guardrail when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(agent_guardrail: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('agent_guardrail')
      end

      it 'omits agent_guardrail when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('agent_guardrail')
      end
      it 'includes anthropic_api_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(anthropic_api_key: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('anthropic_api_key')
      end

      it 'omits anthropic_api_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('anthropic_api_key')
      end
      it 'includes anthropic_key_uuid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(anthropic_key_uuid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('anthropic_key_uuid')
      end

      it 'omits anthropic_key_uuid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('anthropic_key_uuid')
      end
      it 'includes api_key_infos when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(api_key_infos: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('api_key_infos')
      end

      it 'omits api_key_infos when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('api_key_infos')
      end
      it 'includes api_keys when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(api_keys: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('api_keys')
      end

      it 'omits api_keys when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('api_keys')
      end
      it 'includes chatbot when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(chatbot: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('chatbot')
      end

      it 'omits chatbot when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('chatbot')
      end
      it 'includes chatbot_identifiers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(chatbot_identifiers: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('chatbot_identifiers')
      end

      it 'omits chatbot_identifiers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('chatbot_identifiers')
      end
      it 'includes child_agents when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(child_agents: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('child_agents')
      end

      it 'omits child_agents when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('child_agents')
      end
      it 'includes created_at when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(created_at: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('created_at')
      end

      it 'omits created_at when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('created_at')
      end
      it 'includes deployment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(deployment: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('deployment')
      end

      it 'omits deployment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('deployment')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes functions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(functions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('functions')
      end

      it 'omits functions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('functions')
      end
      it 'includes if_case when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(if_case: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('if_case')
      end

      it 'omits if_case when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('if_case')
      end
      it 'includes k when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(k: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('k')
      end

      it 'omits k when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('k')
      end
      it 'includes knowledge_base_uuid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(knowledge_base_uuid: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('knowledge_base_uuid')
      end

      it 'omits knowledge_base_uuid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('knowledge_base_uuid')
      end
      it 'includes knowledge_bases when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(knowledge_bases: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('knowledge_bases')
      end

      it 'omits knowledge_bases when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('knowledge_bases')
      end
      it 'includes max_tokens when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(max_tokens: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('max_tokens')
      end

      it 'omits max_tokens when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('max_tokens')
      end
      it 'includes model when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(model: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('model')
      end

      it 'omits model when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('model')
      end
      it 'includes open_ai_api_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(open_ai_api_key: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('open_ai_api_key')
      end

      it 'omits open_ai_api_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('open_ai_api_key')
      end
      it 'includes open_ai_key_uuid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(open_ai_key_uuid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('open_ai_key_uuid')
      end

      it 'omits open_ai_key_uuid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('open_ai_key_uuid')
      end
      it 'includes parent_agents when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(parent_agents: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('parent_agents')
      end

      it 'omits parent_agents when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('parent_agents')
      end
      it 'includes provide_citations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(provide_citations: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('provide_citations')
      end

      it 'omits provide_citations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('provide_citations')
      end
      it 'includes retrieval_method when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(retrieval_method: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('retrieval_method')
      end

      it 'omits retrieval_method when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('retrieval_method')
      end
      it 'includes route_created_by when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(route_created_by: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('route_created_by')
      end

      it 'omits route_created_by when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('route_created_by')
      end
      it 'includes route_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(route_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('route_name')
      end

      it 'omits route_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('route_name')
      end
      it 'includes route_uuid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(route_uuid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('route_uuid')
      end

      it 'omits route_uuid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('route_uuid')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes temperature when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(temperature: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('temperature')
      end

      it 'omits temperature when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('temperature')
      end
      it 'includes template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(template: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('template')
      end

      it 'omits template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('template')
      end
      it 'includes top_p when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(top_p: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('top_p')
      end

      it 'omits top_p when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('top_p')
      end
      it 'includes url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('url')
      end

      it 'omits url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('url')
      end
      it 'includes user_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(user_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('user_id')
      end

      it 'omits user_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('user_id')
      end
      it 'includes workspace_uuid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('opt', required_attrs.merge(workspace_uuid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'opt')
        expect(config).to have_key('workspace_uuid')
      end

      it 'omits workspace_uuid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'minimal')
        expect(config).not_to have_key('workspace_uuid')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts provide_citations=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(provide_citations: val)
          synth.digitalocean_gradientai_agent("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_gradientai_agent', "bool_#{val}")
          expect(config['provide_citations']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_agent', 'typed')
        expect(config['instruction']).to be_a(String)
        expect(config['model_uuid']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['region']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent('first', required_attrs)
        synth.digitalocean_gradientai_agent('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_gradientai_agent')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_gradientai_agent,
    method: :digitalocean_gradientai_agent,
    required_attrs: { instruction: 'test-value', model_uuid: 'test-value', name: 'test-value', project_id: 'test-value', region: 'test-value' },
    expected_outputs: [:id, :route_created_at, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:provide_citations]
end
