# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_replica resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabaseReplica do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value', name: 'test-value' } }

  describe ':digitalocean_database_replica' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_replica', 'test')
        validate_required_attributes(config, [:cluster_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_replica('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_replica)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_replica('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_replica.test.id}")
        expect(ref.database).to eq("${digitalocean_database_replica.test.database}")
        expect(ref.host).to eq("${digitalocean_database_replica.test.host}")
        expect(ref.password).to eq("${digitalocean_database_replica.test.password}")
        expect(ref.port).to eq("${digitalocean_database_replica.test.port}")
        expect(ref.private_host).to eq("${digitalocean_database_replica.test.private_host}")
        expect(ref.private_network_uuid).to eq("${digitalocean_database_replica.test.private_network_uuid}")
        expect(ref.private_uri).to eq("${digitalocean_database_replica.test.private_uri}")
        expect(ref.storage_size_mib).to eq("${digitalocean_database_replica.test.storage_size_mib}")
        expect(ref.uri).to eq("${digitalocean_database_replica.test.uri}")
        expect(ref.user).to eq("${digitalocean_database_replica.test.user}")
        expect(ref.uuid).to eq("${digitalocean_database_replica.test.uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_replica', 'test')
        expect(config).not_to have_key('database')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('password')
        expect(config).not_to have_key('port')
        expect(config).not_to have_key('private_host')
        expect(config).not_to have_key('private_network_uuid')
        expect(config).not_to have_key('private_uri')
        expect(config).not_to have_key('storage_size_mib')
        expect(config).not_to have_key('uri')
        expect(config).not_to have_key('user')
        expect(config).not_to have_key('uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ region: 'test-value', size: 'test-value', tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_replica', 'full')
        expect(config).to have_key('region')
        expect(config).to have_key('size')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_replica', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_replica', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('opt', required_attrs.merge(size: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_replica', 'opt')
        expect(config).to have_key('size')
      end

      it 'omits size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_replica', 'minimal')
        expect(config).not_to have_key('size')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_replica', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_replica', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password, :private_uri, :uri]
        expect(sensitive_fields).to include(:password)
        expect(sensitive_fields).to include(:private_uri)
        expect(sensitive_fields).to include(:uri)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_replica', 'typed')
        expect(config['cluster_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_replica('first', required_attrs)
        synth.digitalocean_database_replica('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_replica')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_replica,
    method: :digitalocean_database_replica,
    required_attrs: { cluster_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :database, :host, :password, :port, :private_host, :private_network_uuid, :private_uri, :storage_size_mib, :uri, :user, :uuid],
    sensitive_fields: [:password, :private_uri, :uri],
    immutable_fields: [],
    boolean_fields: []
end
