# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_record resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanRecord do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { domain: 'test-value', name: 'test-value', type: 'test-value', value: 'test-value' } }

  describe ':digitalocean_record' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_record', 'test')
        validate_required_attributes(config, [:domain, :name, :type, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_record('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_record)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_record('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_record.test.id}")
        expect(ref.fqdn).to eq("${digitalocean_record.test.fqdn}")
        expect(ref.ttl).to eq("${digitalocean_record.test.ttl}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_record', 'test')
        expect(config).not_to have_key('fqdn')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ flags: 3.14, port: 3.14, priority: 3.14, tag: 'test-value', weight: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_record', 'full')
        expect(config).to have_key('flags')
        expect(config).to have_key('port')
        expect(config).to have_key('priority')
        expect(config).to have_key('tag')
        expect(config).to have_key('weight')
      end
    end

    context 'optional attributes' do
      it 'includes flags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('opt', required_attrs.merge(flags: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'opt')
        expect(config).to have_key('flags')
      end

      it 'omits flags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'minimal')
        expect(config).not_to have_key('flags')
      end
      it 'includes port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('opt', required_attrs.merge(port: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'opt')
        expect(config).to have_key('port')
      end

      it 'omits port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'minimal')
        expect(config).not_to have_key('port')
      end
      it 'includes priority when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('opt', required_attrs.merge(priority: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'opt')
        expect(config).to have_key('priority')
      end

      it 'omits priority when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'minimal')
        expect(config).not_to have_key('priority')
      end
      it 'includes tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('opt', required_attrs.merge(tag: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'opt')
        expect(config).to have_key('tag')
      end

      it 'omits tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'minimal')
        expect(config).not_to have_key('tag')
      end
      it 'includes weight when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('opt', required_attrs.merge(weight: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'opt')
        expect(config).to have_key('weight')
      end

      it 'omits weight when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_record', 'minimal')
        expect(config).not_to have_key('weight')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_record', 'typed')
        expect(config['domain']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_record('first', required_attrs)
        synth.digitalocean_record('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_record')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_record,
    method: :digitalocean_record,
    required_attrs: { domain: 'test-value', name: 'test-value', type: 'test-value', value: 'test-value' },
    expected_outputs: [:id, :fqdn, :ttl],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
