# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_reserved_ipv6 resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanReservedIpv6 do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { region_slug: 'test-value' } }

  describe ':digitalocean_reserved_ipv6' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_reserved_ipv6('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_reserved_ipv6', 'test')
        validate_required_attributes(config, [:region_slug])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_reserved_ipv6('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_reserved_ipv6)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_reserved_ipv6('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_reserved_ipv6.test.id}")
        expect(ref.droplet_id).to eq("${digitalocean_reserved_ipv6.test.droplet_id}")
        expect(ref.ip).to eq("${digitalocean_reserved_ipv6.test.ip}")
        expect(ref.urn).to eq("${digitalocean_reserved_ipv6.test.urn}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_reserved_ipv6('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_reserved_ipv6', 'test')
        expect(config).not_to have_key('droplet_id')
        expect(config).not_to have_key('ip')
        expect(config).not_to have_key('urn')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_reserved_ipv6('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_reserved_ipv6', 'typed')
        expect(config['region_slug']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_reserved_ipv6('first', required_attrs)
        synth.digitalocean_reserved_ipv6('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_reserved_ipv6')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_reserved_ipv6,
    method: :digitalocean_reserved_ipv6,
    required_attrs: { region_slug: 'test-value' },
    expected_outputs: [:id, :droplet_id, :ip, :urn],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
