# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_uptime_alert resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanUptimeAlert do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { check_id: 'test-value', name: 'test-value', notifications: [{ 'key1' => 'val1' }], type: 'test-value' } }

  describe ':digitalocean_uptime_alert' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'test')
        validate_required_attributes(config, [:check_id, :name, :notifications, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_uptime_alert('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_uptime_alert)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_uptime_alert('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_uptime_alert.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comparison: 'test-value', period: 'test-value', threshold: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'full')
        expect(config).to have_key('comparison')
        expect(config).to have_key('period')
        expect(config).to have_key('threshold')
      end
    end

    context 'optional attributes' do
      it 'includes comparison when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('opt', required_attrs.merge(comparison: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'opt')
        expect(config).to have_key('comparison')
      end

      it 'omits comparison when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'minimal')
        expect(config).not_to have_key('comparison')
      end
      it 'includes period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('opt', required_attrs.merge(period: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'opt')
        expect(config).to have_key('period')
      end

      it 'omits period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'minimal')
        expect(config).not_to have_key('period')
      end
      it 'includes threshold when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('opt', required_attrs.merge(threshold: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'opt')
        expect(config).to have_key('threshold')
      end

      it 'omits threshold when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'minimal')
        expect(config).not_to have_key('threshold')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_uptime_alert', 'typed')
        expect(config['check_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['notifications']).to be_a(Array)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_uptime_alert('first', required_attrs)
        synth.digitalocean_uptime_alert('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_uptime_alert')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_uptime_alert,
    method: :digitalocean_uptime_alert,
    required_attrs: { check_id: 'test-value', name: 'test-value', notifications: [{ 'key1' => 'val1' }], type: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
