# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_vpc_nat_gateway resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanVpcNatGateway do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', region: 'test-value', size: 3.14, type: 'test-value', vpcs: [{ 'key1' => 'val1' }] } }

  describe ':digitalocean_vpc_nat_gateway' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_vpc_nat_gateway('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_vpc_nat_gateway', 'test')
        validate_required_attributes(config, [:name, :region, :size, :type, :vpcs])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_vpc_nat_gateway('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_vpc_nat_gateway)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_vpc_nat_gateway('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_vpc_nat_gateway.test.id}")
        expect(ref.created_at).to eq("${digitalocean_vpc_nat_gateway.test.created_at}")
        expect(ref.egresses).to eq("${digitalocean_vpc_nat_gateway.test.egresses}")
        expect(ref.icmp_timeout_seconds).to eq("${digitalocean_vpc_nat_gateway.test.icmp_timeout_seconds}")
        expect(ref.project_id).to eq("${digitalocean_vpc_nat_gateway.test.project_id}")
        expect(ref.state).to eq("${digitalocean_vpc_nat_gateway.test.state}")
        expect(ref.tcp_timeout_seconds).to eq("${digitalocean_vpc_nat_gateway.test.tcp_timeout_seconds}")
        expect(ref.udp_timeout_seconds).to eq("${digitalocean_vpc_nat_gateway.test.udp_timeout_seconds}")
        expect(ref.updated_at).to eq("${digitalocean_vpc_nat_gateway.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_vpc_nat_gateway('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_vpc_nat_gateway', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('egresses')
        expect(config).not_to have_key('icmp_timeout_seconds')
        expect(config).not_to have_key('project_id')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('tcp_timeout_seconds')
        expect(config).not_to have_key('udp_timeout_seconds')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_vpc_nat_gateway('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_vpc_nat_gateway', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['region']).to be_a(String)
        expect(config['size']).to be_a(Float)
        expect(config['type']).to be_a(String)
        expect(config['vpcs']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_vpc_nat_gateway('first', required_attrs)
        synth.digitalocean_vpc_nat_gateway('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_vpc_nat_gateway')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_vpc_nat_gateway,
    method: :digitalocean_vpc_nat_gateway,
    required_attrs: { name: 'test-value', region: 'test-value', size: 3.14, type: 'test-value', vpcs: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :created_at, :egresses, :icmp_timeout_seconds, :project_id, :state, :tcp_timeout_seconds, :udp_timeout_seconds, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
