# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_tag resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanTag do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':digitalocean_tag' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_tag('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_tag', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_tag('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_tag)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_tag('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_tag.test.id}")
        expect(ref.databases_count).to eq("${digitalocean_tag.test.databases_count}")
        expect(ref.droplets_count).to eq("${digitalocean_tag.test.droplets_count}")
        expect(ref.images_count).to eq("${digitalocean_tag.test.images_count}")
        expect(ref.total_resource_count).to eq("${digitalocean_tag.test.total_resource_count}")
        expect(ref.volume_snapshots_count).to eq("${digitalocean_tag.test.volume_snapshots_count}")
        expect(ref.volumes_count).to eq("${digitalocean_tag.test.volumes_count}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_tag('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_tag', 'test')
        expect(config).not_to have_key('databases_count')
        expect(config).not_to have_key('droplets_count')
        expect(config).not_to have_key('images_count')
        expect(config).not_to have_key('total_resource_count')
        expect(config).not_to have_key('volume_snapshots_count')
        expect(config).not_to have_key('volumes_count')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_tag('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_tag', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_tag('first', required_attrs)
        synth.digitalocean_tag('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_tag')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_tag,
    method: :digitalocean_tag,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :databases_count, :droplets_count, :images_count, :total_resource_count, :volume_snapshots_count, :volumes_count],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
