# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_spaces_bucket_cors_configuration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanSpacesBucketCorsConfiguration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { bucket: 'test-value', cors_rule: [{ 'key1' => 'val1' }], region: 'test-value' } }

  describe ':digitalocean_spaces_bucket_cors_configuration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_bucket_cors_configuration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_spaces_bucket_cors_configuration', 'test')
        validate_required_attributes(config, [:bucket, :cors_rule, :region])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_spaces_bucket_cors_configuration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_spaces_bucket_cors_configuration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_spaces_bucket_cors_configuration('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_spaces_bucket_cors_configuration.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_bucket_cors_configuration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_spaces_bucket_cors_configuration', 'typed')
        expect(config['bucket']).to be_a(String)
        expect(config['cors_rule']).to be_a(Array)
        expect(config['region']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_bucket_cors_configuration('first', required_attrs)
        synth.digitalocean_spaces_bucket_cors_configuration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_spaces_bucket_cors_configuration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_spaces_bucket_cors_configuration,
    method: :digitalocean_spaces_bucket_cors_configuration,
    required_attrs: { bucket: 'test-value', cors_rule: [{ 'key1' => 'val1' }], region: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
