# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_kubernetes_cluster resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanKubernetesCluster do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', node_pool: [{ 'key1' => 'val1' }], region: 'test-value', version: 'test-value' } }

  describe ':digitalocean_kubernetes_cluster' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'test')
        validate_required_attributes(config, [:name, :node_pool, :region, :version])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_kubernetes_cluster('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_kubernetes_cluster)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_kubernetes_cluster('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_kubernetes_cluster.test.id}")
        expect(ref.cluster_subnet).to eq("${digitalocean_kubernetes_cluster.test.cluster_subnet}")
        expect(ref.created_at).to eq("${digitalocean_kubernetes_cluster.test.created_at}")
        expect(ref.endpoint).to eq("${digitalocean_kubernetes_cluster.test.endpoint}")
        expect(ref.ipv4_address).to eq("${digitalocean_kubernetes_cluster.test.ipv4_address}")
        expect(ref.kube_config).to eq("${digitalocean_kubernetes_cluster.test.kube_config}")
        expect(ref.service_subnet).to eq("${digitalocean_kubernetes_cluster.test.service_subnet}")
        expect(ref.status).to eq("${digitalocean_kubernetes_cluster.test.status}")
        expect(ref.updated_at).to eq("${digitalocean_kubernetes_cluster.test.updated_at}")
        expect(ref.urn).to eq("${digitalocean_kubernetes_cluster.test.urn}")
        expect(ref.vpc_uuid).to eq("${digitalocean_kubernetes_cluster.test.vpc_uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'test')
        expect(config).not_to have_key('cluster_subnet')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('endpoint')
        expect(config).not_to have_key('ipv4_address')
        expect(config).not_to have_key('kube_config')
        expect(config).not_to have_key('service_subnet')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('urn')
        expect(config).not_to have_key('vpc_uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ amd_gpu_device_metrics_exporter_plugin: [{ 'key1' => 'val1' }], amd_gpu_device_plugin: [{ 'key1' => 'val1' }], auto_upgrade: true, cluster_autoscaler_configuration: [{ 'key1' => 'val1' }], control_plane_firewall: [{ 'key1' => 'val1' }], destroy_all_associated_resources: true, ha: true, kubeconfig_expire_seconds: 3.14, maintenance_policy: [{ 'key1' => 'val1' }], nvidia_gpu_device_plugin: [{ 'key1' => 'val1' }], rdma_shared_device_plugin: [{ 'key1' => 'val1' }], registry_integration: true, routing_agent: [{ 'key1' => 'val1' }], sso: [{ 'key1' => 'val1' }], surge_upgrade: true, tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'full')
        expect(config).to have_key('amd_gpu_device_metrics_exporter_plugin')
        expect(config).to have_key('amd_gpu_device_plugin')
        expect(config).to have_key('auto_upgrade')
        expect(config).to have_key('cluster_autoscaler_configuration')
        expect(config).to have_key('control_plane_firewall')
        expect(config).to have_key('destroy_all_associated_resources')
        expect(config).to have_key('ha')
        expect(config).to have_key('kubeconfig_expire_seconds')
        expect(config).to have_key('maintenance_policy')
        expect(config).to have_key('nvidia_gpu_device_plugin')
        expect(config).to have_key('rdma_shared_device_plugin')
        expect(config).to have_key('registry_integration')
        expect(config).to have_key('routing_agent')
        expect(config).to have_key('sso')
        expect(config).to have_key('surge_upgrade')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes amd_gpu_device_metrics_exporter_plugin when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(amd_gpu_device_metrics_exporter_plugin: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('amd_gpu_device_metrics_exporter_plugin')
      end

      it 'omits amd_gpu_device_metrics_exporter_plugin when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('amd_gpu_device_metrics_exporter_plugin')
      end
      it 'includes amd_gpu_device_plugin when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(amd_gpu_device_plugin: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('amd_gpu_device_plugin')
      end

      it 'omits amd_gpu_device_plugin when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('amd_gpu_device_plugin')
      end
      it 'includes auto_upgrade when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(auto_upgrade: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('auto_upgrade')
      end

      it 'omits auto_upgrade when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('auto_upgrade')
      end
      it 'includes cluster_autoscaler_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(cluster_autoscaler_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('cluster_autoscaler_configuration')
      end

      it 'omits cluster_autoscaler_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('cluster_autoscaler_configuration')
      end
      it 'includes control_plane_firewall when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(control_plane_firewall: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('control_plane_firewall')
      end

      it 'omits control_plane_firewall when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('control_plane_firewall')
      end
      it 'includes destroy_all_associated_resources when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(destroy_all_associated_resources: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('destroy_all_associated_resources')
      end

      it 'omits destroy_all_associated_resources when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('destroy_all_associated_resources')
      end
      it 'includes ha when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(ha: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('ha')
      end

      it 'omits ha when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('ha')
      end
      it 'includes kubeconfig_expire_seconds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(kubeconfig_expire_seconds: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('kubeconfig_expire_seconds')
      end

      it 'omits kubeconfig_expire_seconds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('kubeconfig_expire_seconds')
      end
      it 'includes maintenance_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(maintenance_policy: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('maintenance_policy')
      end

      it 'omits maintenance_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('maintenance_policy')
      end
      it 'includes nvidia_gpu_device_plugin when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(nvidia_gpu_device_plugin: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('nvidia_gpu_device_plugin')
      end

      it 'omits nvidia_gpu_device_plugin when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('nvidia_gpu_device_plugin')
      end
      it 'includes rdma_shared_device_plugin when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(rdma_shared_device_plugin: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('rdma_shared_device_plugin')
      end

      it 'omits rdma_shared_device_plugin when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('rdma_shared_device_plugin')
      end
      it 'includes registry_integration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(registry_integration: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('registry_integration')
      end

      it 'omits registry_integration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('registry_integration')
      end
      it 'includes routing_agent when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(routing_agent: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('routing_agent')
      end

      it 'omits routing_agent when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('routing_agent')
      end
      it 'includes sso when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(sso: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('sso')
      end

      it 'omits sso when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('sso')
      end
      it 'includes surge_upgrade when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(surge_upgrade: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('surge_upgrade')
      end

      it 'omits surge_upgrade when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('surge_upgrade')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:kube_config]
        expect(sensitive_fields).to include(:kube_config)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts auto_upgrade=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_upgrade: val)
          synth.digitalocean_kubernetes_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', "bool_#{val}")
          expect(config['auto_upgrade']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts destroy_all_associated_resources=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(destroy_all_associated_resources: val)
          synth.digitalocean_kubernetes_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', "bool_#{val}")
          expect(config['destroy_all_associated_resources']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ha=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ha: val)
          synth.digitalocean_kubernetes_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', "bool_#{val}")
          expect(config['ha']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts registry_integration=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(registry_integration: val)
          synth.digitalocean_kubernetes_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', "bool_#{val}")
          expect(config['registry_integration']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts surge_upgrade=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(surge_upgrade: val)
          synth.digitalocean_kubernetes_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', "bool_#{val}")
          expect(config['surge_upgrade']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_kubernetes_cluster', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['node_pool']).to be_a(Array)
        expect(config['region']).to be_a(String)
        expect(config['version']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_cluster('first', required_attrs)
        synth.digitalocean_kubernetes_cluster('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_kubernetes_cluster')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_kubernetes_cluster,
    method: :digitalocean_kubernetes_cluster,
    required_attrs: { name: 'test-value', node_pool: [{ 'key1' => 'val1' }], region: 'test-value', version: 'test-value' },
    expected_outputs: [:id, :cluster_subnet, :created_at, :endpoint, :ipv4_address, :kube_config, :service_subnet, :status, :updated_at, :urn, :vpc_uuid],
    sensitive_fields: [:kube_config],
    immutable_fields: [],
    boolean_fields: [:auto_upgrade, :destroy_all_associated_resources, :ha, :registry_integration, :surge_upgrade]
end
