# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_opensearch_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabaseOpensearchConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value' } }

  describe ':digitalocean_database_opensearch_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_opensearch_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_opensearch_config', 'test')
        validate_required_attributes(config, [:cluster_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_opensearch_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_opensearch_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_opensearch_config('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_opensearch_config.test.id}")
        expect(ref.action_auto_create_index_enabled).to eq("${digitalocean_database_opensearch_config.test.action_auto_create_index_enabled}")
        expect(ref.action_destructive_requires_name).to eq("${digitalocean_database_opensearch_config.test.action_destructive_requires_name}")
        expect(ref.cluster_max_shards_per_node).to eq("${digitalocean_database_opensearch_config.test.cluster_max_shards_per_node}")
        expect(ref.cluster_routing_allocation_node_concurrent_recoveries).to eq("${digitalocean_database_opensearch_config.test.cluster_routing_allocation_node_concurrent_recoveries}")
        expect(ref.enable_security_audit).to eq("${digitalocean_database_opensearch_config.test.enable_security_audit}")
        expect(ref.http_max_content_length_bytes).to eq("${digitalocean_database_opensearch_config.test.http_max_content_length_bytes}")
        expect(ref.http_max_header_size_bytes).to eq("${digitalocean_database_opensearch_config.test.http_max_header_size_bytes}")
        expect(ref.http_max_initial_line_length_bytes).to eq("${digitalocean_database_opensearch_config.test.http_max_initial_line_length_bytes}")
        expect(ref.indices_fielddata_cache_size_percentage).to eq("${digitalocean_database_opensearch_config.test.indices_fielddata_cache_size_percentage}")
        expect(ref.indices_memory_index_buffer_size_percentage).to eq("${digitalocean_database_opensearch_config.test.indices_memory_index_buffer_size_percentage}")
        expect(ref.indices_memory_max_index_buffer_size_mb).to eq("${digitalocean_database_opensearch_config.test.indices_memory_max_index_buffer_size_mb}")
        expect(ref.indices_memory_min_index_buffer_size_mb).to eq("${digitalocean_database_opensearch_config.test.indices_memory_min_index_buffer_size_mb}")
        expect(ref.indices_queries_cache_size_percentage).to eq("${digitalocean_database_opensearch_config.test.indices_queries_cache_size_percentage}")
        expect(ref.indices_query_bool_max_clause_count).to eq("${digitalocean_database_opensearch_config.test.indices_query_bool_max_clause_count}")
        expect(ref.indices_recovery_max_concurrent_file_chunks).to eq("${digitalocean_database_opensearch_config.test.indices_recovery_max_concurrent_file_chunks}")
        expect(ref.indices_recovery_max_mb_per_sec).to eq("${digitalocean_database_opensearch_config.test.indices_recovery_max_mb_per_sec}")
        expect(ref.ism_enabled).to eq("${digitalocean_database_opensearch_config.test.ism_enabled}")
        expect(ref.ism_history_enabled).to eq("${digitalocean_database_opensearch_config.test.ism_history_enabled}")
        expect(ref.ism_history_max_age_hours).to eq("${digitalocean_database_opensearch_config.test.ism_history_max_age_hours}")
        expect(ref.ism_history_max_docs).to eq("${digitalocean_database_opensearch_config.test.ism_history_max_docs}")
        expect(ref.ism_history_rollover_check_period_hours).to eq("${digitalocean_database_opensearch_config.test.ism_history_rollover_check_period_hours}")
        expect(ref.ism_history_rollover_retention_period_days).to eq("${digitalocean_database_opensearch_config.test.ism_history_rollover_retention_period_days}")
        expect(ref.override_main_response_version).to eq("${digitalocean_database_opensearch_config.test.override_main_response_version}")
        expect(ref.plugins_alerting_filter_by_backend_roles_enabled).to eq("${digitalocean_database_opensearch_config.test.plugins_alerting_filter_by_backend_roles_enabled}")
        expect(ref.script_max_compilations_rate).to eq("${digitalocean_database_opensearch_config.test.script_max_compilations_rate}")
        expect(ref.search_max_buckets).to eq("${digitalocean_database_opensearch_config.test.search_max_buckets}")
        expect(ref.thread_pool_analyze_queue_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_analyze_queue_size}")
        expect(ref.thread_pool_analyze_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_analyze_size}")
        expect(ref.thread_pool_force_merge_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_force_merge_size}")
        expect(ref.thread_pool_get_queue_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_get_queue_size}")
        expect(ref.thread_pool_get_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_get_size}")
        expect(ref.thread_pool_search_queue_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_search_queue_size}")
        expect(ref.thread_pool_search_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_search_size}")
        expect(ref.thread_pool_search_throttled_queue_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_search_throttled_queue_size}")
        expect(ref.thread_pool_search_throttled_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_search_throttled_size}")
        expect(ref.thread_pool_write_queue_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_write_queue_size}")
        expect(ref.thread_pool_write_size).to eq("${digitalocean_database_opensearch_config.test.thread_pool_write_size}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_opensearch_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_opensearch_config', 'test')
        expect(config).not_to have_key('action_auto_create_index_enabled')
        expect(config).not_to have_key('action_destructive_requires_name')
        expect(config).not_to have_key('cluster_max_shards_per_node')
        expect(config).not_to have_key('cluster_routing_allocation_node_concurrent_recoveries')
        expect(config).not_to have_key('enable_security_audit')
        expect(config).not_to have_key('http_max_content_length_bytes')
        expect(config).not_to have_key('http_max_header_size_bytes')
        expect(config).not_to have_key('http_max_initial_line_length_bytes')
        expect(config).not_to have_key('indices_fielddata_cache_size_percentage')
        expect(config).not_to have_key('indices_memory_index_buffer_size_percentage')
        expect(config).not_to have_key('indices_memory_max_index_buffer_size_mb')
        expect(config).not_to have_key('indices_memory_min_index_buffer_size_mb')
        expect(config).not_to have_key('indices_queries_cache_size_percentage')
        expect(config).not_to have_key('indices_query_bool_max_clause_count')
        expect(config).not_to have_key('indices_recovery_max_concurrent_file_chunks')
        expect(config).not_to have_key('indices_recovery_max_mb_per_sec')
        expect(config).not_to have_key('ism_enabled')
        expect(config).not_to have_key('ism_history_enabled')
        expect(config).not_to have_key('ism_history_max_age_hours')
        expect(config).not_to have_key('ism_history_max_docs')
        expect(config).not_to have_key('ism_history_rollover_check_period_hours')
        expect(config).not_to have_key('ism_history_rollover_retention_period_days')
        expect(config).not_to have_key('override_main_response_version')
        expect(config).not_to have_key('plugins_alerting_filter_by_backend_roles_enabled')
        expect(config).not_to have_key('script_max_compilations_rate')
        expect(config).not_to have_key('search_max_buckets')
        expect(config).not_to have_key('thread_pool_analyze_queue_size')
        expect(config).not_to have_key('thread_pool_analyze_size')
        expect(config).not_to have_key('thread_pool_force_merge_size')
        expect(config).not_to have_key('thread_pool_get_queue_size')
        expect(config).not_to have_key('thread_pool_get_size')
        expect(config).not_to have_key('thread_pool_search_queue_size')
        expect(config).not_to have_key('thread_pool_search_size')
        expect(config).not_to have_key('thread_pool_search_throttled_queue_size')
        expect(config).not_to have_key('thread_pool_search_throttled_size')
        expect(config).not_to have_key('thread_pool_write_queue_size')
        expect(config).not_to have_key('thread_pool_write_size')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ reindex_remote_whitelist: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_opensearch_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_opensearch_config', 'full')
        expect(config).to have_key('reindex_remote_whitelist')
      end
    end

    context 'optional attributes' do
      it 'includes reindex_remote_whitelist when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_opensearch_config('opt', required_attrs.merge(reindex_remote_whitelist: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_opensearch_config', 'opt')
        expect(config).to have_key('reindex_remote_whitelist')
      end

      it 'omits reindex_remote_whitelist when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_opensearch_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_opensearch_config', 'minimal')
        expect(config).not_to have_key('reindex_remote_whitelist')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_opensearch_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_opensearch_config', 'typed')
        expect(config['cluster_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_opensearch_config('first', required_attrs)
        synth.digitalocean_database_opensearch_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_opensearch_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_opensearch_config,
    method: :digitalocean_database_opensearch_config,
    required_attrs: { cluster_id: 'test-value' },
    expected_outputs: [:id, :action_auto_create_index_enabled, :action_destructive_requires_name, :cluster_max_shards_per_node, :cluster_routing_allocation_node_concurrent_recoveries, :enable_security_audit, :http_max_content_length_bytes, :http_max_header_size_bytes, :http_max_initial_line_length_bytes, :indices_fielddata_cache_size_percentage, :indices_memory_index_buffer_size_percentage, :indices_memory_max_index_buffer_size_mb, :indices_memory_min_index_buffer_size_mb, :indices_queries_cache_size_percentage, :indices_query_bool_max_clause_count, :indices_recovery_max_concurrent_file_chunks, :indices_recovery_max_mb_per_sec, :ism_enabled, :ism_history_enabled, :ism_history_max_age_hours, :ism_history_max_docs, :ism_history_rollover_check_period_hours, :ism_history_rollover_retention_period_days, :override_main_response_version, :plugins_alerting_filter_by_backend_roles_enabled, :script_max_compilations_rate, :search_max_buckets, :thread_pool_analyze_queue_size, :thread_pool_analyze_size, :thread_pool_force_merge_size, :thread_pool_get_queue_size, :thread_pool_get_size, :thread_pool_search_queue_size, :thread_pool_search_size, :thread_pool_search_throttled_queue_size, :thread_pool_search_throttled_size, :thread_pool_write_queue_size, :thread_pool_write_size],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
