# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_container_registry_docker_credentials resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanContainerRegistryDockerCredentials do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { registry_name: 'test-value' } }

  describe ':digitalocean_container_registry_docker_credentials' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', 'test')
        validate_required_attributes(config, [:registry_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_container_registry_docker_credentials('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_container_registry_docker_credentials)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_container_registry_docker_credentials('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_container_registry_docker_credentials.test.id}")
        expect(ref.credential_expiration_time).to eq("${digitalocean_container_registry_docker_credentials.test.credential_expiration_time}")
        expect(ref.docker_credentials).to eq("${digitalocean_container_registry_docker_credentials.test.docker_credentials}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', 'test')
        expect(config).not_to have_key('credential_expiration_time')
        expect(config).not_to have_key('docker_credentials')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ expiry_seconds: 3.14, write: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', 'full')
        expect(config).to have_key('expiry_seconds')
        expect(config).to have_key('write')
      end
    end

    context 'optional attributes' do
      it 'includes expiry_seconds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('opt', required_attrs.merge(expiry_seconds: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', 'opt')
        expect(config).to have_key('expiry_seconds')
      end

      it 'omits expiry_seconds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', 'minimal')
        expect(config).not_to have_key('expiry_seconds')
      end
      it 'includes write when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('opt', required_attrs.merge(write: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', 'opt')
        expect(config).to have_key('write')
      end

      it 'omits write when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', 'minimal')
        expect(config).not_to have_key('write')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:docker_credentials]
        expect(sensitive_fields).to include(:docker_credentials)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts write=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(write: val)
          synth.digitalocean_container_registry_docker_credentials("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', "bool_#{val}")
          expect(config['write']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_container_registry_docker_credentials', 'typed')
        expect(config['registry_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_container_registry_docker_credentials('first', required_attrs)
        synth.digitalocean_container_registry_docker_credentials('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_container_registry_docker_credentials')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_container_registry_docker_credentials,
    method: :digitalocean_container_registry_docker_credentials,
    required_attrs: { registry_name: 'test-value' },
    expected_outputs: [:id, :credential_expiration_time, :docker_credentials],
    sensitive_fields: [:docker_credentials],
    immutable_fields: [],
    boolean_fields: [:write]
end
