# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_floating_ip resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanFloatingIp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { region: 'test-value' } }

  describe ':digitalocean_floating_ip' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_floating_ip('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_floating_ip', 'test')
        validate_required_attributes(config, [:region])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_floating_ip('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_floating_ip)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_floating_ip('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_floating_ip.test.id}")
        expect(ref.ip_address).to eq("${digitalocean_floating_ip.test.ip_address}")
        expect(ref.urn).to eq("${digitalocean_floating_ip.test.urn}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_floating_ip('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_floating_ip', 'test')
        expect(config).not_to have_key('ip_address')
        expect(config).not_to have_key('urn')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ droplet_id: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_floating_ip('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_floating_ip', 'full')
        expect(config).to have_key('droplet_id')
      end
    end

    context 'optional attributes' do
      it 'includes droplet_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_floating_ip('opt', required_attrs.merge(droplet_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_floating_ip', 'opt')
        expect(config).to have_key('droplet_id')
      end

      it 'omits droplet_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_floating_ip('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_floating_ip', 'minimal')
        expect(config).not_to have_key('droplet_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_floating_ip('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_floating_ip', 'typed')
        expect(config['region']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_floating_ip('first', required_attrs)
        synth.digitalocean_floating_ip('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_floating_ip')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_floating_ip,
    method: :digitalocean_floating_ip,
    required_attrs: { region: 'test-value' },
    expected_outputs: [:id, :ip_address, :urn],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
