# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_gradientai_indexing_job_cancel resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanGradientaiIndexingJobCancel do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { uuid: 'test-value' } }

  describe ':digitalocean_gradientai_indexing_job_cancel' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_indexing_job_cancel('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_gradientai_indexing_job_cancel', 'test')
        validate_required_attributes(config, [:uuid])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_indexing_job_cancel('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_gradientai_indexing_job_cancel)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_indexing_job_cancel('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_gradientai_indexing_job_cancel.test.id}")
        expect(ref.completed_datasources).to eq("${digitalocean_gradientai_indexing_job_cancel.test.completed_datasources}")
        expect(ref.created_at).to eq("${digitalocean_gradientai_indexing_job_cancel.test.created_at}")
        expect(ref.data_source_uuids).to eq("${digitalocean_gradientai_indexing_job_cancel.test.data_source_uuids}")
        expect(ref.finished_at).to eq("${digitalocean_gradientai_indexing_job_cancel.test.finished_at}")
        expect(ref.knowledge_base_uuid).to eq("${digitalocean_gradientai_indexing_job_cancel.test.knowledge_base_uuid}")
        expect(ref.phase).to eq("${digitalocean_gradientai_indexing_job_cancel.test.phase}")
        expect(ref.started_at).to eq("${digitalocean_gradientai_indexing_job_cancel.test.started_at}")
        expect(ref.status).to eq("${digitalocean_gradientai_indexing_job_cancel.test.status}")
        expect(ref.tokens).to eq("${digitalocean_gradientai_indexing_job_cancel.test.tokens}")
        expect(ref.total_datasources).to eq("${digitalocean_gradientai_indexing_job_cancel.test.total_datasources}")
        expect(ref.total_items_failed).to eq("${digitalocean_gradientai_indexing_job_cancel.test.total_items_failed}")
        expect(ref.total_items_indexed).to eq("${digitalocean_gradientai_indexing_job_cancel.test.total_items_indexed}")
        expect(ref.total_items_skipped).to eq("${digitalocean_gradientai_indexing_job_cancel.test.total_items_skipped}")
        expect(ref.updated_at).to eq("${digitalocean_gradientai_indexing_job_cancel.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_indexing_job_cancel('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_indexing_job_cancel', 'test')
        expect(config).not_to have_key('completed_datasources')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('data_source_uuids')
        expect(config).not_to have_key('finished_at')
        expect(config).not_to have_key('knowledge_base_uuid')
        expect(config).not_to have_key('phase')
        expect(config).not_to have_key('started_at')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('tokens')
        expect(config).not_to have_key('total_datasources')
        expect(config).not_to have_key('total_items_failed')
        expect(config).not_to have_key('total_items_indexed')
        expect(config).not_to have_key('total_items_skipped')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_indexing_job_cancel('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_indexing_job_cancel', 'typed')
        expect(config['uuid']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_indexing_job_cancel('first', required_attrs)
        synth.digitalocean_gradientai_indexing_job_cancel('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_gradientai_indexing_job_cancel')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_gradientai_indexing_job_cancel,
    method: :digitalocean_gradientai_indexing_job_cancel,
    required_attrs: { uuid: 'test-value' },
    expected_outputs: [:id, :completed_datasources, :created_at, :data_source_uuids, :finished_at, :knowledge_base_uuid, :phase, :started_at, :status, :tokens, :total_datasources, :total_items_failed, :total_items_indexed, :total_items_skipped, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
