# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_cdn resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanCdn do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { origin: 'test-value' } }

  describe ':digitalocean_cdn' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_cdn('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_cdn', 'test')
        validate_required_attributes(config, [:origin])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_cdn('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_cdn)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_cdn('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_cdn.test.id}")
        expect(ref.certificate_id).to eq("${digitalocean_cdn.test.certificate_id}")
        expect(ref.certificate_name).to eq("${digitalocean_cdn.test.certificate_name}")
        expect(ref.created_at).to eq("${digitalocean_cdn.test.created_at}")
        expect(ref.endpoint).to eq("${digitalocean_cdn.test.endpoint}")
        expect(ref.ttl).to eq("${digitalocean_cdn.test.ttl}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_cdn('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_cdn', 'test')
        expect(config).not_to have_key('certificate_id')
        expect(config).not_to have_key('certificate_name')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('endpoint')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_domain: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_cdn('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_cdn', 'full')
        expect(config).to have_key('custom_domain')
      end
    end

    context 'optional attributes' do
      it 'includes custom_domain when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_cdn('opt', required_attrs.merge(custom_domain: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_cdn', 'opt')
        expect(config).to have_key('custom_domain')
      end

      it 'omits custom_domain when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_cdn('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_cdn', 'minimal')
        expect(config).not_to have_key('custom_domain')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_cdn('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_cdn', 'typed')
        expect(config['origin']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_cdn('first', required_attrs)
        synth.digitalocean_cdn('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_cdn')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_cdn,
    method: :digitalocean_cdn,
    required_attrs: { origin: 'test-value' },
    expected_outputs: [:id, :certificate_id, :certificate_name, :created_at, :endpoint, :ttl],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
