# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_certificate resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanCertificate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':digitalocean_certificate' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_certificate('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_certificate)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_certificate('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_certificate.test.id}")
        expect(ref.not_after).to eq("${digitalocean_certificate.test.not_after}")
        expect(ref.sha1_fingerprint).to eq("${digitalocean_certificate.test.sha1_fingerprint}")
        expect(ref.state).to eq("${digitalocean_certificate.test.state}")
        expect(ref.uuid).to eq("${digitalocean_certificate.test.uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_certificate', 'test')
        expect(config).not_to have_key('not_after')
        expect(config).not_to have_key('sha1_fingerprint')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ certificate_chain: 'test-value', domains: ['test-value'], leaf_certificate: 'test-value', private_key: 'test-value', type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_certificate', 'full')
        expect(config).to have_key('certificate_chain')
        expect(config).to have_key('domains')
        expect(config).to have_key('leaf_certificate')
        expect(config).to have_key('private_key')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes certificate_chain when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('opt', required_attrs.merge(certificate_chain: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'opt')
        expect(config).to have_key('certificate_chain')
      end

      it 'omits certificate_chain when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'minimal')
        expect(config).not_to have_key('certificate_chain')
      end
      it 'includes domains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('opt', required_attrs.merge(domains: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'opt')
        expect(config).to have_key('domains')
      end

      it 'omits domains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'minimal')
        expect(config).not_to have_key('domains')
      end
      it 'includes leaf_certificate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('opt', required_attrs.merge(leaf_certificate: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'opt')
        expect(config).to have_key('leaf_certificate')
      end

      it 'omits leaf_certificate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'minimal')
        expect(config).not_to have_key('leaf_certificate')
      end
      it 'includes private_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('opt', required_attrs.merge(private_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'opt')
        expect(config).to have_key('private_key')
      end

      it 'omits private_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'minimal')
        expect(config).not_to have_key('private_key')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_certificate', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:private_key]
        expect(sensitive_fields).to include(:private_key)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_certificate', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_certificate('first', required_attrs)
        synth.digitalocean_certificate('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_certificate')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_certificate,
    method: :digitalocean_certificate,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :not_after, :sha1_fingerprint, :state, :uuid],
    sensitive_fields: [:private_key],
    immutable_fields: [],
    boolean_fields: []
end
