# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_gradientai_knowledge_base_data_source resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanGradientaiKnowledgeBaseDataSource do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { knowledge_base_uuid: 'test-value' } }

  describe ':digitalocean_gradientai_knowledge_base_data_source' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_knowledge_base_data_source('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_gradientai_knowledge_base_data_source', 'test')
        validate_required_attributes(config, [:knowledge_base_uuid])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_knowledge_base_data_source('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_gradientai_knowledge_base_data_source)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_knowledge_base_data_source('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_gradientai_knowledge_base_data_source.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ spaces_data_source: [{ 'key1' => 'val1' }], web_crawler_data_source: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_knowledge_base_data_source('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_knowledge_base_data_source', 'full')
        expect(config).to have_key('spaces_data_source')
        expect(config).to have_key('web_crawler_data_source')
      end
    end

    context 'optional attributes' do
      it 'includes spaces_data_source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_knowledge_base_data_source('opt', required_attrs.merge(spaces_data_source: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_knowledge_base_data_source', 'opt')
        expect(config).to have_key('spaces_data_source')
      end

      it 'omits spaces_data_source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_knowledge_base_data_source('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_knowledge_base_data_source', 'minimal')
        expect(config).not_to have_key('spaces_data_source')
      end
      it 'includes web_crawler_data_source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_knowledge_base_data_source('opt', required_attrs.merge(web_crawler_data_source: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_knowledge_base_data_source', 'opt')
        expect(config).to have_key('web_crawler_data_source')
      end

      it 'omits web_crawler_data_source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_knowledge_base_data_source('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_knowledge_base_data_source', 'minimal')
        expect(config).not_to have_key('web_crawler_data_source')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_knowledge_base_data_source('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_knowledge_base_data_source', 'typed')
        expect(config['knowledge_base_uuid']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_knowledge_base_data_source('first', required_attrs)
        synth.digitalocean_gradientai_knowledge_base_data_source('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_gradientai_knowledge_base_data_source')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_gradientai_knowledge_base_data_source,
    method: :digitalocean_gradientai_knowledge_base_data_source,
    required_attrs: { knowledge_base_uuid: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
