# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_custom_image resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanCustomImage do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', regions: ['test-value'], url: 'test-value' } }

  describe ':digitalocean_custom_image' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_custom_image', 'test')
        validate_required_attributes(config, [:name, :regions, :url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_custom_image('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_custom_image)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_custom_image('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_custom_image.test.id}")
        expect(ref.created_at).to eq("${digitalocean_custom_image.test.created_at}")
        expect(ref.image_id).to eq("${digitalocean_custom_image.test.image_id}")
        expect(ref.min_disk_size).to eq("${digitalocean_custom_image.test.min_disk_size}")
        expect(ref.public).to eq("${digitalocean_custom_image.test.public}")
        expect(ref.size_gigabytes).to eq("${digitalocean_custom_image.test.size_gigabytes}")
        expect(ref.slug).to eq("${digitalocean_custom_image.test.slug}")
        expect(ref.status).to eq("${digitalocean_custom_image.test.status}")
        expect(ref.type).to eq("${digitalocean_custom_image.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_custom_image', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('image_id')
        expect(config).not_to have_key('min_disk_size')
        expect(config).not_to have_key('public')
        expect(config).not_to have_key('size_gigabytes')
        expect(config).not_to have_key('slug')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', distribution: 'test-value', tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_custom_image', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('distribution')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_custom_image', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_custom_image', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes distribution when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('opt', required_attrs.merge(distribution: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_custom_image', 'opt')
        expect(config).to have_key('distribution')
      end

      it 'omits distribution when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_custom_image', 'minimal')
        expect(config).not_to have_key('distribution')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_custom_image', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_custom_image', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_custom_image', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['regions']).to be_a(Array)
        expect(config['url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_custom_image('first', required_attrs)
        synth.digitalocean_custom_image('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_custom_image')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_custom_image,
    method: :digitalocean_custom_image,
    required_attrs: { name: 'test-value', regions: ['test-value'], url: 'test-value' },
    expected_outputs: [:id, :created_at, :image_id, :min_disk_size, :public, :size_gigabytes, :slug, :status, :type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
