# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_online_migration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabaseOnlineMigration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value', source: [{ 'key1' => 'val1' }] } }

  describe ':digitalocean_database_online_migration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_online_migration', 'test')
        validate_required_attributes(config, [:cluster_id, :source])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_online_migration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_online_migration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_online_migration('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_online_migration.test.id}")
        expect(ref.created_at).to eq("${digitalocean_database_online_migration.test.created_at}")
        expect(ref.status).to eq("${digitalocean_database_online_migration.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_online_migration', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ disable_ssl: true, ignore_dbs: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_online_migration', 'full')
        expect(config).to have_key('disable_ssl')
        expect(config).to have_key('ignore_dbs')
      end
    end

    context 'optional attributes' do
      it 'includes disable_ssl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('opt', required_attrs.merge(disable_ssl: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_online_migration', 'opt')
        expect(config).to have_key('disable_ssl')
      end

      it 'omits disable_ssl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_online_migration', 'minimal')
        expect(config).not_to have_key('disable_ssl')
      end
      it 'includes ignore_dbs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('opt', required_attrs.merge(ignore_dbs: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_online_migration', 'opt')
        expect(config).to have_key('ignore_dbs')
      end

      it 'omits ignore_dbs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_online_migration', 'minimal')
        expect(config).not_to have_key('ignore_dbs')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_ssl=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_ssl: val)
          synth.digitalocean_database_online_migration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_database_online_migration', "bool_#{val}")
          expect(config['disable_ssl']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_online_migration', 'typed')
        expect(config['cluster_id']).to be_a(String)
        expect(config['source']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_online_migration('first', required_attrs)
        synth.digitalocean_database_online_migration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_online_migration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_online_migration,
    method: :digitalocean_database_online_migration,
    required_attrs: { cluster_id: 'test-value', source: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :created_at, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disable_ssl]
end
