# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_app resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanApp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':digitalocean_app' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_app', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_app('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_app)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_app('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_app.test.id}")
        expect(ref.active_deployment_id).to eq("${digitalocean_app.test.active_deployment_id}")
        expect(ref.created_at).to eq("${digitalocean_app.test.created_at}")
        expect(ref.default_ingress).to eq("${digitalocean_app.test.default_ingress}")
        expect(ref.live_domain).to eq("${digitalocean_app.test.live_domain}")
        expect(ref.live_url).to eq("${digitalocean_app.test.live_url}")
        expect(ref.project_id).to eq("${digitalocean_app.test.project_id}")
        expect(ref.updated_at).to eq("${digitalocean_app.test.updated_at}")
        expect(ref.urn).to eq("${digitalocean_app.test.urn}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_app', 'test')
        expect(config).not_to have_key('active_deployment_id')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('default_ingress')
        expect(config).not_to have_key('live_domain')
        expect(config).not_to have_key('live_url')
        expect(config).not_to have_key('project_id')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('urn')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ dedicated_ips: [{ 'key1' => 'val1' }], deployment_per_page: 3.14, spec: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_app', 'full')
        expect(config).to have_key('dedicated_ips')
        expect(config).to have_key('deployment_per_page')
        expect(config).to have_key('spec')
      end
    end

    context 'optional attributes' do
      it 'includes dedicated_ips when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('opt', required_attrs.merge(dedicated_ips: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_app', 'opt')
        expect(config).to have_key('dedicated_ips')
      end

      it 'omits dedicated_ips when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_app', 'minimal')
        expect(config).not_to have_key('dedicated_ips')
      end
      it 'includes deployment_per_page when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('opt', required_attrs.merge(deployment_per_page: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_app', 'opt')
        expect(config).to have_key('deployment_per_page')
      end

      it 'omits deployment_per_page when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_app', 'minimal')
        expect(config).not_to have_key('deployment_per_page')
      end
      it 'includes spec when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('opt', required_attrs.merge(spec: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_app', 'opt')
        expect(config).to have_key('spec')
      end

      it 'omits spec when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_app', 'minimal')
        expect(config).not_to have_key('spec')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_app', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_app('first', required_attrs)
        synth.digitalocean_app('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_app')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_app,
    method: :digitalocean_app,
    required_attrs: {},
    expected_outputs: [:id, :active_deployment_id, :created_at, :default_ingress, :live_domain, :live_url, :project_id, :updated_at, :urn],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
