# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_gradientai_function resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanGradientaiFunction do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { agent_id: 'test-value', description: 'test-value', faas_namespace: 'test-value', function_name: 'test-value', input_schema: 'test-value' } }

  describe ':digitalocean_gradientai_function' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_gradientai_function', 'test')
        validate_required_attributes(config, [:agent_id, :description, :faas_namespace, :function_name, :input_schema])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_function('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_gradientai_function)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_function('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_gradientai_function.test.id}")
        expect(ref.function_uuid).to eq("${digitalocean_gradientai_function.test.function_uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_function', 'test')
        expect(config).not_to have_key('function_uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ faas_name: 'test-value', output_schema: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_function', 'full')
        expect(config).to have_key('faas_name')
        expect(config).to have_key('output_schema')
      end
    end

    context 'optional attributes' do
      it 'includes faas_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('opt', required_attrs.merge(faas_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_function', 'opt')
        expect(config).to have_key('faas_name')
      end

      it 'omits faas_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_function', 'minimal')
        expect(config).not_to have_key('faas_name')
      end
      it 'includes output_schema when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('opt', required_attrs.merge(output_schema: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_function', 'opt')
        expect(config).to have_key('output_schema')
      end

      it 'omits output_schema when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_function', 'minimal')
        expect(config).not_to have_key('output_schema')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_function', 'typed')
        expect(config['agent_id']).to be_a(String)
        expect(config['description']).to be_a(String)
        expect(config['faas_namespace']).to be_a(String)
        expect(config['function_name']).to be_a(String)
        expect(config['input_schema']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_function('first', required_attrs)
        synth.digitalocean_gradientai_function('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_gradientai_function')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_gradientai_function,
    method: :digitalocean_gradientai_function,
    required_attrs: { agent_id: 'test-value', description: 'test-value', faas_namespace: 'test-value', function_name: 'test-value', input_schema: 'test-value' },
    expected_outputs: [:id, :function_uuid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
