# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_kafka_topic resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabaseKafkaTopic do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value', name: 'test-value' } }

  describe ':digitalocean_database_kafka_topic' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'test')
        validate_required_attributes(config, [:cluster_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_kafka_topic('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_kafka_topic)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_kafka_topic('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_kafka_topic.test.id}")
        expect(ref.state).to eq("${digitalocean_database_kafka_topic.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'test')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ config: [{ 'key1' => 'val1' }], partition_count: 3.14, replication_factor: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'full')
        expect(config).to have_key('config')
        expect(config).to have_key('partition_count')
        expect(config).to have_key('replication_factor')
      end
    end

    context 'optional attributes' do
      it 'includes config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('opt', required_attrs.merge(config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'opt')
        expect(config).to have_key('config')
      end

      it 'omits config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'minimal')
        expect(config).not_to have_key('config')
      end
      it 'includes partition_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('opt', required_attrs.merge(partition_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'opt')
        expect(config).to have_key('partition_count')
      end

      it 'omits partition_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'minimal')
        expect(config).not_to have_key('partition_count')
      end
      it 'includes replication_factor when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('opt', required_attrs.merge(replication_factor: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'opt')
        expect(config).to have_key('replication_factor')
      end

      it 'omits replication_factor when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'minimal')
        expect(config).not_to have_key('replication_factor')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_kafka_topic', 'typed')
        expect(config['cluster_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_kafka_topic('first', required_attrs)
        synth.digitalocean_database_kafka_topic('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_kafka_topic')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_kafka_topic,
    method: :digitalocean_database_kafka_topic,
    required_attrs: { cluster_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
