# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_nfs_snapshot resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanNfsSnapshot do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', region: 'test-value', share_id: 'test-value' } }

  describe ':digitalocean_nfs_snapshot' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs_snapshot('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_nfs_snapshot', 'test')
        validate_required_attributes(config, [:name, :region, :share_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_nfs_snapshot('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_nfs_snapshot)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_nfs_snapshot('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_nfs_snapshot.test.id}")
        expect(ref.created_at).to eq("${digitalocean_nfs_snapshot.test.created_at}")
        expect(ref.size).to eq("${digitalocean_nfs_snapshot.test.size}")
        expect(ref.status).to eq("${digitalocean_nfs_snapshot.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs_snapshot('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_nfs_snapshot', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('size')
        expect(config).not_to have_key('status')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs_snapshot('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_nfs_snapshot', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['region']).to be_a(String)
        expect(config['share_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs_snapshot('first', required_attrs)
        synth.digitalocean_nfs_snapshot('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_nfs_snapshot')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_nfs_snapshot,
    method: :digitalocean_nfs_snapshot,
    required_attrs: { name: 'test-value', region: 'test-value', share_id: 'test-value' },
    expected_outputs: [:id, :created_at, :size, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
