# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_project resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanProject do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':digitalocean_project' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_project', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_project('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_project)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_project('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_project.test.id}")
        expect(ref.created_at).to eq("${digitalocean_project.test.created_at}")
        expect(ref.owner_id).to eq("${digitalocean_project.test.owner_id}")
        expect(ref.owner_uuid).to eq("${digitalocean_project.test.owner_uuid}")
        expect(ref.resources).to eq("${digitalocean_project.test.resources}")
        expect(ref.updated_at).to eq("${digitalocean_project.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_project', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('owner_id')
        expect(config).not_to have_key('owner_uuid')
        expect(config).not_to have_key('resources')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', environment: 'test-value', is_default: true, purpose: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_project', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('environment')
        expect(config).to have_key('is_default')
        expect(config).to have_key('purpose')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_project', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_project', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes environment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('opt', required_attrs.merge(environment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_project', 'opt')
        expect(config).to have_key('environment')
      end

      it 'omits environment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_project', 'minimal')
        expect(config).not_to have_key('environment')
      end
      it 'includes is_default when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('opt', required_attrs.merge(is_default: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_project', 'opt')
        expect(config).to have_key('is_default')
      end

      it 'omits is_default when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_project', 'minimal')
        expect(config).not_to have_key('is_default')
      end
      it 'includes purpose when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('opt', required_attrs.merge(purpose: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_project', 'opt')
        expect(config).to have_key('purpose')
      end

      it 'omits purpose when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_project', 'minimal')
        expect(config).not_to have_key('purpose')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts is_default=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_default: val)
          synth.digitalocean_project("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_project', "bool_#{val}")
          expect(config['is_default']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_project', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_project('first', required_attrs)
        synth.digitalocean_project('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_project')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_project,
    method: :digitalocean_project,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :created_at, :owner_id, :owner_uuid, :resources, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:is_default]
end
