# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_loadbalancer resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanLoadbalancer do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':digitalocean_loadbalancer' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_loadbalancer('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_loadbalancer)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_loadbalancer('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_loadbalancer.test.id}")
        expect(ref.droplet_ids).to eq("${digitalocean_loadbalancer.test.droplet_ids}")
        expect(ref.http_idle_timeout_seconds).to eq("${digitalocean_loadbalancer.test.http_idle_timeout_seconds}")
        expect(ref.ip).to eq("${digitalocean_loadbalancer.test.ip}")
        expect(ref.ipv6).to eq("${digitalocean_loadbalancer.test.ipv6}")
        expect(ref.project_id).to eq("${digitalocean_loadbalancer.test.project_id}")
        expect(ref.size_unit).to eq("${digitalocean_loadbalancer.test.size_unit}")
        expect(ref.status).to eq("${digitalocean_loadbalancer.test.status}")
        expect(ref.target_load_balancer_ids).to eq("${digitalocean_loadbalancer.test.target_load_balancer_ids}")
        expect(ref.type).to eq("${digitalocean_loadbalancer.test.type}")
        expect(ref.urn).to eq("${digitalocean_loadbalancer.test.urn}")
        expect(ref.vpc_uuid).to eq("${digitalocean_loadbalancer.test.vpc_uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'test')
        expect(config).not_to have_key('droplet_ids')
        expect(config).not_to have_key('http_idle_timeout_seconds')
        expect(config).not_to have_key('ip')
        expect(config).not_to have_key('ipv6')
        expect(config).not_to have_key('project_id')
        expect(config).not_to have_key('size_unit')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('target_load_balancer_ids')
        expect(config).not_to have_key('type')
        expect(config).not_to have_key('urn')
        expect(config).not_to have_key('vpc_uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ algorithm: 'test-value', disable_lets_encrypt_dns_records: true, domains: [{ 'key1' => 'val1' }], droplet_tag: 'test-value', enable_backend_keepalive: true, enable_proxy_protocol: true, firewall: [{ 'key1' => 'val1' }], forwarding_rule: [{ 'key1' => 'val1' }], glb_settings: [{ 'key1' => 'val1' }], healthcheck: [{ 'key1' => 'val1' }], network: 'test-value', network_stack: 'test-value', redirect_http_to_https: true, region: 'test-value', size: 'test-value', sticky_sessions: [{ 'key1' => 'val1' }], tls_cipher_policy: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'full')
        expect(config).to have_key('algorithm')
        expect(config).to have_key('disable_lets_encrypt_dns_records')
        expect(config).to have_key('domains')
        expect(config).to have_key('droplet_tag')
        expect(config).to have_key('enable_backend_keepalive')
        expect(config).to have_key('enable_proxy_protocol')
        expect(config).to have_key('firewall')
        expect(config).to have_key('forwarding_rule')
        expect(config).to have_key('glb_settings')
        expect(config).to have_key('healthcheck')
        expect(config).to have_key('network')
        expect(config).to have_key('network_stack')
        expect(config).to have_key('redirect_http_to_https')
        expect(config).to have_key('region')
        expect(config).to have_key('size')
        expect(config).to have_key('sticky_sessions')
        expect(config).to have_key('tls_cipher_policy')
      end
    end

    context 'optional attributes' do
      it 'includes algorithm when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(algorithm: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('algorithm')
      end

      it 'omits algorithm when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('algorithm')
      end
      it 'includes disable_lets_encrypt_dns_records when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(disable_lets_encrypt_dns_records: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('disable_lets_encrypt_dns_records')
      end

      it 'omits disable_lets_encrypt_dns_records when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('disable_lets_encrypt_dns_records')
      end
      it 'includes domains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(domains: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('domains')
      end

      it 'omits domains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('domains')
      end
      it 'includes droplet_tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(droplet_tag: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('droplet_tag')
      end

      it 'omits droplet_tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('droplet_tag')
      end
      it 'includes enable_backend_keepalive when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(enable_backend_keepalive: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('enable_backend_keepalive')
      end

      it 'omits enable_backend_keepalive when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('enable_backend_keepalive')
      end
      it 'includes enable_proxy_protocol when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(enable_proxy_protocol: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('enable_proxy_protocol')
      end

      it 'omits enable_proxy_protocol when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('enable_proxy_protocol')
      end
      it 'includes firewall when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(firewall: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('firewall')
      end

      it 'omits firewall when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('firewall')
      end
      it 'includes forwarding_rule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(forwarding_rule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('forwarding_rule')
      end

      it 'omits forwarding_rule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('forwarding_rule')
      end
      it 'includes glb_settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(glb_settings: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('glb_settings')
      end

      it 'omits glb_settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('glb_settings')
      end
      it 'includes healthcheck when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(healthcheck: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('healthcheck')
      end

      it 'omits healthcheck when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('healthcheck')
      end
      it 'includes network when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(network: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('network')
      end

      it 'omits network when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('network')
      end
      it 'includes network_stack when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(network_stack: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('network_stack')
      end

      it 'omits network_stack when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('network_stack')
      end
      it 'includes redirect_http_to_https when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(redirect_http_to_https: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('redirect_http_to_https')
      end

      it 'omits redirect_http_to_https when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('redirect_http_to_https')
      end
      it 'includes region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('region')
      end

      it 'omits region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('region')
      end
      it 'includes size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(size: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('size')
      end

      it 'omits size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('size')
      end
      it 'includes sticky_sessions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(sticky_sessions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('sticky_sessions')
      end

      it 'omits sticky_sessions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('sticky_sessions')
      end
      it 'includes tls_cipher_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('opt', required_attrs.merge(tls_cipher_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'opt')
        expect(config).to have_key('tls_cipher_policy')
      end

      it 'omits tls_cipher_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'minimal')
        expect(config).not_to have_key('tls_cipher_policy')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_lets_encrypt_dns_records=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_lets_encrypt_dns_records: val)
          synth.digitalocean_loadbalancer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_loadbalancer', "bool_#{val}")
          expect(config['disable_lets_encrypt_dns_records']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_backend_keepalive=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_backend_keepalive: val)
          synth.digitalocean_loadbalancer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_loadbalancer', "bool_#{val}")
          expect(config['enable_backend_keepalive']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_proxy_protocol=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_proxy_protocol: val)
          synth.digitalocean_loadbalancer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_loadbalancer', "bool_#{val}")
          expect(config['enable_proxy_protocol']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts redirect_http_to_https=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(redirect_http_to_https: val)
          synth.digitalocean_loadbalancer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_loadbalancer', "bool_#{val}")
          expect(config['redirect_http_to_https']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_loadbalancer', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_loadbalancer('first', required_attrs)
        synth.digitalocean_loadbalancer('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_loadbalancer')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_loadbalancer,
    method: :digitalocean_loadbalancer,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :droplet_ids, :http_idle_timeout_seconds, :ip, :ipv6, :project_id, :size_unit, :status, :target_load_balancer_ids, :type, :urn, :vpc_uuid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disable_lets_encrypt_dns_records, :enable_backend_keepalive, :enable_proxy_protocol, :redirect_http_to_https]
end
