# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_monitor_alert resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanMonitorAlert do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { alerts: [{ 'key1' => 'val1' }], compare: 'test-value', description: 'test-value', type: 'test-value', value: 3.14, window: 'test-value' } }

  describe ':digitalocean_monitor_alert' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'test')
        validate_required_attributes(config, [:alerts, :compare, :description, :type, :value, :window])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_monitor_alert('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_monitor_alert)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_monitor_alert('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_monitor_alert.test.id}")
        expect(ref.uuid).to eq("${digitalocean_monitor_alert.test.uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'test')
        expect(config).not_to have_key('uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ enabled: true, entities: ['test-value'], tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'full')
        expect(config).to have_key('enabled')
        expect(config).to have_key('entities')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes entities when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('opt', required_attrs.merge(entities: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'opt')
        expect(config).to have_key('entities')
      end

      it 'omits entities when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'minimal')
        expect(config).not_to have_key('entities')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.digitalocean_monitor_alert("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_monitor_alert', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_monitor_alert', 'typed')
        expect(config['alerts']).to be_a(Array)
        expect(config['compare']).to be_a(String)
        expect(config['description']).to be_a(String)
        expect(config['type']).to be_a(String)
        expect(config['value']).to be_a(Float)
        expect(config['window']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_monitor_alert('first', required_attrs)
        synth.digitalocean_monitor_alert('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_monitor_alert')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_monitor_alert,
    method: :digitalocean_monitor_alert,
    required_attrs: { alerts: [{ 'key1' => 'val1' }], compare: 'test-value', description: 'test-value', type: 'test-value', value: 3.14, window: 'test-value' },
    expected_outputs: [:id, :uuid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
