# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_droplet resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDroplet do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { image: 'test-value', name: 'test-value', size: 'test-value' } }

  describe ':digitalocean_droplet' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'test')
        validate_required_attributes(config, [:image, :name, :size])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_droplet('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_droplet)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_droplet('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_droplet.test.id}")
        expect(ref.created_at).to eq("${digitalocean_droplet.test.created_at}")
        expect(ref.disk).to eq("${digitalocean_droplet.test.disk}")
        expect(ref.ipv4_address).to eq("${digitalocean_droplet.test.ipv4_address}")
        expect(ref.ipv4_address_private).to eq("${digitalocean_droplet.test.ipv4_address_private}")
        expect(ref.ipv6_address).to eq("${digitalocean_droplet.test.ipv6_address}")
        expect(ref.locked).to eq("${digitalocean_droplet.test.locked}")
        expect(ref.memory).to eq("${digitalocean_droplet.test.memory}")
        expect(ref.price_hourly).to eq("${digitalocean_droplet.test.price_hourly}")
        expect(ref.price_monthly).to eq("${digitalocean_droplet.test.price_monthly}")
        expect(ref.private_networking).to eq("${digitalocean_droplet.test.private_networking}")
        expect(ref.region).to eq("${digitalocean_droplet.test.region}")
        expect(ref.status).to eq("${digitalocean_droplet.test.status}")
        expect(ref.urn).to eq("${digitalocean_droplet.test.urn}")
        expect(ref.vcpus).to eq("${digitalocean_droplet.test.vcpus}")
        expect(ref.volume_ids).to eq("${digitalocean_droplet.test.volume_ids}")
        expect(ref.vpc_uuid).to eq("${digitalocean_droplet.test.vpc_uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_droplet', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('disk')
        expect(config).not_to have_key('ipv4_address')
        expect(config).not_to have_key('ipv4_address_private')
        expect(config).not_to have_key('ipv6_address')
        expect(config).not_to have_key('locked')
        expect(config).not_to have_key('memory')
        expect(config).not_to have_key('price_hourly')
        expect(config).not_to have_key('price_monthly')
        expect(config).not_to have_key('private_networking')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('urn')
        expect(config).not_to have_key('vcpus')
        expect(config).not_to have_key('volume_ids')
        expect(config).not_to have_key('vpc_uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ backup_policy: [{ 'key1' => 'val1' }], backups: true, droplet_agent: true, graceful_shutdown: true, ipv6: true, monitoring: true, resize_disk: true, ssh_keys: ['test-value'], tags: ['test-value'], user_data: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_droplet', 'full')
        expect(config).to have_key('backup_policy')
        expect(config).to have_key('backups')
        expect(config).to have_key('droplet_agent')
        expect(config).to have_key('graceful_shutdown')
        expect(config).to have_key('ipv6')
        expect(config).to have_key('monitoring')
        expect(config).to have_key('resize_disk')
        expect(config).to have_key('ssh_keys')
        expect(config).to have_key('tags')
        expect(config).to have_key('user_data')
      end
    end

    context 'optional attributes' do
      it 'includes backup_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(backup_policy: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('backup_policy')
      end

      it 'omits backup_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('backup_policy')
      end
      it 'includes backups when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(backups: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('backups')
      end

      it 'omits backups when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('backups')
      end
      it 'includes droplet_agent when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(droplet_agent: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('droplet_agent')
      end

      it 'omits droplet_agent when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('droplet_agent')
      end
      it 'includes graceful_shutdown when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(graceful_shutdown: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('graceful_shutdown')
      end

      it 'omits graceful_shutdown when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('graceful_shutdown')
      end
      it 'includes ipv6 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(ipv6: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('ipv6')
      end

      it 'omits ipv6 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('ipv6')
      end
      it 'includes monitoring when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(monitoring: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('monitoring')
      end

      it 'omits monitoring when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('monitoring')
      end
      it 'includes resize_disk when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(resize_disk: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('resize_disk')
      end

      it 'omits resize_disk when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('resize_disk')
      end
      it 'includes ssh_keys when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(ssh_keys: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('ssh_keys')
      end

      it 'omits ssh_keys when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('ssh_keys')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes user_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('opt', required_attrs.merge(user_data: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'opt')
        expect(config).to have_key('user_data')
      end

      it 'omits user_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_droplet', 'minimal')
        expect(config).not_to have_key('user_data')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts backups=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(backups: val)
          synth.digitalocean_droplet("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_droplet', "bool_#{val}")
          expect(config['backups']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts droplet_agent=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(droplet_agent: val)
          synth.digitalocean_droplet("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_droplet', "bool_#{val}")
          expect(config['droplet_agent']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts graceful_shutdown=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(graceful_shutdown: val)
          synth.digitalocean_droplet("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_droplet', "bool_#{val}")
          expect(config['graceful_shutdown']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ipv6=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ipv6: val)
          synth.digitalocean_droplet("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_droplet', "bool_#{val}")
          expect(config['ipv6']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts monitoring=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(monitoring: val)
          synth.digitalocean_droplet("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_droplet', "bool_#{val}")
          expect(config['monitoring']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts resize_disk=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(resize_disk: val)
          synth.digitalocean_droplet("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_droplet', "bool_#{val}")
          expect(config['resize_disk']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_droplet', 'typed')
        expect(config['image']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['size']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_droplet('first', required_attrs)
        synth.digitalocean_droplet('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_droplet')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_droplet,
    method: :digitalocean_droplet,
    required_attrs: { image: 'test-value', name: 'test-value', size: 'test-value' },
    expected_outputs: [:id, :created_at, :disk, :ipv4_address, :ipv4_address_private, :ipv6_address, :locked, :memory, :price_hourly, :price_monthly, :private_networking, :region, :status, :urn, :vcpus, :volume_ids, :vpc_uuid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:backups, :droplet_agent, :graceful_shutdown, :ipv6, :monitoring, :resize_disk]
end
