# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_nfs resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanNfs do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', region: 'test-value', size: 3.14, vpc_id: 'test-value' } }

  describe ':digitalocean_nfs' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_nfs', 'test')
        validate_required_attributes(config, [:name, :region, :size, :vpc_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_nfs('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_nfs)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_nfs('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_nfs.test.id}")
        expect(ref.host).to eq("${digitalocean_nfs.test.host}")
        expect(ref.mount_path).to eq("${digitalocean_nfs.test.mount_path}")
        expect(ref.status).to eq("${digitalocean_nfs.test.status}")
        expect(ref.vpc_ids).to eq("${digitalocean_nfs.test.vpc_ids}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_nfs', 'test')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('mount_path')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('vpc_ids')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ performance_tier: 'test-value', tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_nfs', 'full')
        expect(config).to have_key('performance_tier')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes performance_tier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('opt', required_attrs.merge(performance_tier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_nfs', 'opt')
        expect(config).to have_key('performance_tier')
      end

      it 'omits performance_tier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_nfs', 'minimal')
        expect(config).not_to have_key('performance_tier')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_nfs', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_nfs', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_nfs', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['region']).to be_a(String)
        expect(config['size']).to be_a(Float)
        expect(config['vpc_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_nfs('first', required_attrs)
        synth.digitalocean_nfs('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_nfs')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_nfs,
    method: :digitalocean_nfs,
    required_attrs: { name: 'test-value', region: 'test-value', size: 3.14, vpc_id: 'test-value' },
    expected_outputs: [:id, :host, :mount_path, :status, :vpc_ids],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
