# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_kubernetes_node_pool resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanKubernetesNodePool do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value', name: 'test-value', size: 'test-value' } }

  describe ':digitalocean_kubernetes_node_pool' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'test')
        validate_required_attributes(config, [:cluster_id, :name, :size])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_kubernetes_node_pool('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_kubernetes_node_pool)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_kubernetes_node_pool('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_kubernetes_node_pool.test.id}")
        expect(ref.actual_node_count).to eq("${digitalocean_kubernetes_node_pool.test.actual_node_count}")
        expect(ref.nodes).to eq("${digitalocean_kubernetes_node_pool.test.nodes}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'test')
        expect(config).not_to have_key('actual_node_count')
        expect(config).not_to have_key('nodes')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ auto_scale: true, labels: { 'key1' => 'val1' }, max_nodes: 3.14, min_nodes: 3.14, node_count: 3.14, tags: ['test-value'], taint: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'full')
        expect(config).to have_key('auto_scale')
        expect(config).to have_key('labels')
        expect(config).to have_key('max_nodes')
        expect(config).to have_key('min_nodes')
        expect(config).to have_key('node_count')
        expect(config).to have_key('tags')
        expect(config).to have_key('taint')
      end
    end

    context 'optional attributes' do
      it 'includes auto_scale when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('opt', required_attrs.merge(auto_scale: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'opt')
        expect(config).to have_key('auto_scale')
      end

      it 'omits auto_scale when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'minimal')
        expect(config).not_to have_key('auto_scale')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes max_nodes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('opt', required_attrs.merge(max_nodes: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'opt')
        expect(config).to have_key('max_nodes')
      end

      it 'omits max_nodes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'minimal')
        expect(config).not_to have_key('max_nodes')
      end
      it 'includes min_nodes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('opt', required_attrs.merge(min_nodes: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'opt')
        expect(config).to have_key('min_nodes')
      end

      it 'omits min_nodes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'minimal')
        expect(config).not_to have_key('min_nodes')
      end
      it 'includes node_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('opt', required_attrs.merge(node_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'opt')
        expect(config).to have_key('node_count')
      end

      it 'omits node_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'minimal')
        expect(config).not_to have_key('node_count')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes taint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('opt', required_attrs.merge(taint: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'opt')
        expect(config).to have_key('taint')
      end

      it 'omits taint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'minimal')
        expect(config).not_to have_key('taint')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts auto_scale=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_scale: val)
          synth.digitalocean_kubernetes_node_pool("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', "bool_#{val}")
          expect(config['auto_scale']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_kubernetes_node_pool', 'typed')
        expect(config['cluster_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['size']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_kubernetes_node_pool('first', required_attrs)
        synth.digitalocean_kubernetes_node_pool('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_kubernetes_node_pool')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_kubernetes_node_pool,
    method: :digitalocean_kubernetes_node_pool,
    required_attrs: { cluster_id: 'test-value', name: 'test-value', size: 'test-value' },
    expected_outputs: [:id, :actual_node_count, :nodes],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:auto_scale]
end
