# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_byoip_prefix resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanByoipPrefix do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { prefix: 'test-value', region: 'test-value' } }

  describe ':digitalocean_byoip_prefix' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_byoip_prefix', 'test')
        validate_required_attributes(config, [:prefix, :region])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_byoip_prefix('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_byoip_prefix)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_byoip_prefix('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_byoip_prefix.test.id}")
        expect(ref.failure_reason).to eq("${digitalocean_byoip_prefix.test.failure_reason}")
        expect(ref.status).to eq("${digitalocean_byoip_prefix.test.status}")
        expect(ref.uuid).to eq("${digitalocean_byoip_prefix.test.uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_byoip_prefix', 'test')
        expect(config).not_to have_key('failure_reason')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ advertised: true, signature: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_byoip_prefix', 'full')
        expect(config).to have_key('advertised')
        expect(config).to have_key('signature')
      end
    end

    context 'optional attributes' do
      it 'includes advertised when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('opt', required_attrs.merge(advertised: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_byoip_prefix', 'opt')
        expect(config).to have_key('advertised')
      end

      it 'omits advertised when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_byoip_prefix', 'minimal')
        expect(config).not_to have_key('advertised')
      end
      it 'includes signature when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('opt', required_attrs.merge(signature: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_byoip_prefix', 'opt')
        expect(config).to have_key('signature')
      end

      it 'omits signature when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_byoip_prefix', 'minimal')
        expect(config).not_to have_key('signature')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts advertised=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(advertised: val)
          synth.digitalocean_byoip_prefix("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'digitalocean_byoip_prefix', "bool_#{val}")
          expect(config['advertised']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_byoip_prefix', 'typed')
        expect(config['prefix']).to be_a(String)
        expect(config['region']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_byoip_prefix('first', required_attrs)
        synth.digitalocean_byoip_prefix('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_byoip_prefix')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_byoip_prefix,
    method: :digitalocean_byoip_prefix,
    required_attrs: { prefix: 'test-value', region: 'test-value' },
    expected_outputs: [:id, :failure_reason, :status, :uuid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:advertised]
end
