# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_spaces_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanSpacesKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':digitalocean_spaces_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_spaces_key', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_spaces_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_spaces_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_spaces_key('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_spaces_key.test.id}")
        expect(ref.access_key).to eq("${digitalocean_spaces_key.test.access_key}")
        expect(ref.created_at).to eq("${digitalocean_spaces_key.test.created_at}")
        expect(ref.secret_key).to eq("${digitalocean_spaces_key.test.secret_key}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_spaces_key', 'test')
        expect(config).not_to have_key('access_key')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('secret_key')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ grant: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_key('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_spaces_key', 'full')
        expect(config).to have_key('grant')
      end
    end

    context 'optional attributes' do
      it 'includes grant when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_key('opt', required_attrs.merge(grant: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_spaces_key', 'opt')
        expect(config).to have_key('grant')
      end

      it 'omits grant when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_spaces_key', 'minimal')
        expect(config).not_to have_key('grant')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:secret_key]
        expect(sensitive_fields).to include(:secret_key)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_spaces_key', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_spaces_key('first', required_attrs)
        synth.digitalocean_spaces_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_spaces_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_spaces_key,
    method: :digitalocean_spaces_key,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :access_key, :created_at, :secret_key],
    sensitive_fields: [:secret_key],
    immutable_fields: [],
    boolean_fields: []
end
