# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_gradientai_openai_api_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanGradientaiOpenaiApiKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_key: 'test-value', name: 'test-value' } }

  describe ':digitalocean_gradientai_openai_api_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_openai_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_gradientai_openai_api_key', 'test')
        validate_required_attributes(config, [:api_key, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_openai_api_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_gradientai_openai_api_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_openai_api_key('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_gradientai_openai_api_key.test.id}")
        expect(ref.created_at).to eq("${digitalocean_gradientai_openai_api_key.test.created_at}")
        expect(ref.created_by).to eq("${digitalocean_gradientai_openai_api_key.test.created_by}")
        expect(ref.deleted_at).to eq("${digitalocean_gradientai_openai_api_key.test.deleted_at}")
        expect(ref.updated_at).to eq("${digitalocean_gradientai_openai_api_key.test.updated_at}")
        expect(ref.uuid).to eq("${digitalocean_gradientai_openai_api_key.test.uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_openai_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_openai_api_key', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('created_by')
        expect(config).not_to have_key('deleted_at')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ model: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_openai_api_key('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_openai_api_key', 'full')
        expect(config).to have_key('model')
      end
    end

    context 'optional attributes' do
      it 'includes model when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_openai_api_key('opt', required_attrs.merge(model: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_openai_api_key', 'opt')
        expect(config).to have_key('model')
      end

      it 'omits model when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_openai_api_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_gradientai_openai_api_key', 'minimal')
        expect(config).not_to have_key('model')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_openai_api_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_openai_api_key', 'typed')
        expect(config['api_key']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_openai_api_key('first', required_attrs)
        synth.digitalocean_gradientai_openai_api_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_gradientai_openai_api_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_gradientai_openai_api_key,
    method: :digitalocean_gradientai_openai_api_key,
    required_attrs: { api_key: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :created_at, :created_by, :deleted_at, :updated_at, :uuid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
