# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_postgresql_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabasePostgresqlConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value' } }

  describe ':digitalocean_database_postgresql_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_postgresql_config', 'test')
        validate_required_attributes(config, [:cluster_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_postgresql_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_postgresql_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_postgresql_config('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_postgresql_config.test.id}")
        expect(ref.autovacuum_analyze_scale_factor).to eq("${digitalocean_database_postgresql_config.test.autovacuum_analyze_scale_factor}")
        expect(ref.autovacuum_analyze_threshold).to eq("${digitalocean_database_postgresql_config.test.autovacuum_analyze_threshold}")
        expect(ref.autovacuum_freeze_max_age).to eq("${digitalocean_database_postgresql_config.test.autovacuum_freeze_max_age}")
        expect(ref.autovacuum_max_workers).to eq("${digitalocean_database_postgresql_config.test.autovacuum_max_workers}")
        expect(ref.autovacuum_naptime).to eq("${digitalocean_database_postgresql_config.test.autovacuum_naptime}")
        expect(ref.autovacuum_vacuum_cost_delay).to eq("${digitalocean_database_postgresql_config.test.autovacuum_vacuum_cost_delay}")
        expect(ref.autovacuum_vacuum_cost_limit).to eq("${digitalocean_database_postgresql_config.test.autovacuum_vacuum_cost_limit}")
        expect(ref.autovacuum_vacuum_scale_factor).to eq("${digitalocean_database_postgresql_config.test.autovacuum_vacuum_scale_factor}")
        expect(ref.autovacuum_vacuum_threshold).to eq("${digitalocean_database_postgresql_config.test.autovacuum_vacuum_threshold}")
        expect(ref.backup_hour).to eq("${digitalocean_database_postgresql_config.test.backup_hour}")
        expect(ref.backup_minute).to eq("${digitalocean_database_postgresql_config.test.backup_minute}")
        expect(ref.bgwriter_delay).to eq("${digitalocean_database_postgresql_config.test.bgwriter_delay}")
        expect(ref.bgwriter_flush_after).to eq("${digitalocean_database_postgresql_config.test.bgwriter_flush_after}")
        expect(ref.bgwriter_lru_maxpages).to eq("${digitalocean_database_postgresql_config.test.bgwriter_lru_maxpages}")
        expect(ref.bgwriter_lru_multiplier).to eq("${digitalocean_database_postgresql_config.test.bgwriter_lru_multiplier}")
        expect(ref.deadlock_timeout).to eq("${digitalocean_database_postgresql_config.test.deadlock_timeout}")
        expect(ref.default_toast_compression).to eq("${digitalocean_database_postgresql_config.test.default_toast_compression}")
        expect(ref.idle_in_transaction_session_timeout).to eq("${digitalocean_database_postgresql_config.test.idle_in_transaction_session_timeout}")
        expect(ref.jit).to eq("${digitalocean_database_postgresql_config.test.jit}")
        expect(ref.log_autovacuum_min_duration).to eq("${digitalocean_database_postgresql_config.test.log_autovacuum_min_duration}")
        expect(ref.log_error_verbosity).to eq("${digitalocean_database_postgresql_config.test.log_error_verbosity}")
        expect(ref.log_line_prefix).to eq("${digitalocean_database_postgresql_config.test.log_line_prefix}")
        expect(ref.log_min_duration_statement).to eq("${digitalocean_database_postgresql_config.test.log_min_duration_statement}")
        expect(ref.max_files_per_process).to eq("${digitalocean_database_postgresql_config.test.max_files_per_process}")
        expect(ref.max_locks_per_transaction).to eq("${digitalocean_database_postgresql_config.test.max_locks_per_transaction}")
        expect(ref.max_logical_replication_workers).to eq("${digitalocean_database_postgresql_config.test.max_logical_replication_workers}")
        expect(ref.max_parallel_workers).to eq("${digitalocean_database_postgresql_config.test.max_parallel_workers}")
        expect(ref.max_parallel_workers_per_gather).to eq("${digitalocean_database_postgresql_config.test.max_parallel_workers_per_gather}")
        expect(ref.max_pred_locks_per_transaction).to eq("${digitalocean_database_postgresql_config.test.max_pred_locks_per_transaction}")
        expect(ref.max_prepared_transactions).to eq("${digitalocean_database_postgresql_config.test.max_prepared_transactions}")
        expect(ref.max_replication_slots).to eq("${digitalocean_database_postgresql_config.test.max_replication_slots}")
        expect(ref.max_stack_depth).to eq("${digitalocean_database_postgresql_config.test.max_stack_depth}")
        expect(ref.max_standby_archive_delay).to eq("${digitalocean_database_postgresql_config.test.max_standby_archive_delay}")
        expect(ref.max_standby_streaming_delay).to eq("${digitalocean_database_postgresql_config.test.max_standby_streaming_delay}")
        expect(ref.max_wal_senders).to eq("${digitalocean_database_postgresql_config.test.max_wal_senders}")
        expect(ref.max_worker_processes).to eq("${digitalocean_database_postgresql_config.test.max_worker_processes}")
        expect(ref.pg_partman_bgw_interval).to eq("${digitalocean_database_postgresql_config.test.pg_partman_bgw_interval}")
        expect(ref.pg_partman_bgw_role).to eq("${digitalocean_database_postgresql_config.test.pg_partman_bgw_role}")
        expect(ref.pg_stat_statements_track).to eq("${digitalocean_database_postgresql_config.test.pg_stat_statements_track}")
        expect(ref.shared_buffers_percentage).to eq("${digitalocean_database_postgresql_config.test.shared_buffers_percentage}")
        expect(ref.temp_file_limit).to eq("${digitalocean_database_postgresql_config.test.temp_file_limit}")
        expect(ref.timezone).to eq("${digitalocean_database_postgresql_config.test.timezone}")
        expect(ref.track_activity_query_size).to eq("${digitalocean_database_postgresql_config.test.track_activity_query_size}")
        expect(ref.track_commit_timestamp).to eq("${digitalocean_database_postgresql_config.test.track_commit_timestamp}")
        expect(ref.track_functions).to eq("${digitalocean_database_postgresql_config.test.track_functions}")
        expect(ref.track_io_timing).to eq("${digitalocean_database_postgresql_config.test.track_io_timing}")
        expect(ref.wal_sender_timeout).to eq("${digitalocean_database_postgresql_config.test.wal_sender_timeout}")
        expect(ref.wal_writer_delay).to eq("${digitalocean_database_postgresql_config.test.wal_writer_delay}")
        expect(ref.work_mem).to eq("${digitalocean_database_postgresql_config.test.work_mem}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_postgresql_config', 'test')
        expect(config).not_to have_key('autovacuum_analyze_scale_factor')
        expect(config).not_to have_key('autovacuum_analyze_threshold')
        expect(config).not_to have_key('autovacuum_freeze_max_age')
        expect(config).not_to have_key('autovacuum_max_workers')
        expect(config).not_to have_key('autovacuum_naptime')
        expect(config).not_to have_key('autovacuum_vacuum_cost_delay')
        expect(config).not_to have_key('autovacuum_vacuum_cost_limit')
        expect(config).not_to have_key('autovacuum_vacuum_scale_factor')
        expect(config).not_to have_key('autovacuum_vacuum_threshold')
        expect(config).not_to have_key('backup_hour')
        expect(config).not_to have_key('backup_minute')
        expect(config).not_to have_key('bgwriter_delay')
        expect(config).not_to have_key('bgwriter_flush_after')
        expect(config).not_to have_key('bgwriter_lru_maxpages')
        expect(config).not_to have_key('bgwriter_lru_multiplier')
        expect(config).not_to have_key('deadlock_timeout')
        expect(config).not_to have_key('default_toast_compression')
        expect(config).not_to have_key('idle_in_transaction_session_timeout')
        expect(config).not_to have_key('jit')
        expect(config).not_to have_key('log_autovacuum_min_duration')
        expect(config).not_to have_key('log_error_verbosity')
        expect(config).not_to have_key('log_line_prefix')
        expect(config).not_to have_key('log_min_duration_statement')
        expect(config).not_to have_key('max_files_per_process')
        expect(config).not_to have_key('max_locks_per_transaction')
        expect(config).not_to have_key('max_logical_replication_workers')
        expect(config).not_to have_key('max_parallel_workers')
        expect(config).not_to have_key('max_parallel_workers_per_gather')
        expect(config).not_to have_key('max_pred_locks_per_transaction')
        expect(config).not_to have_key('max_prepared_transactions')
        expect(config).not_to have_key('max_replication_slots')
        expect(config).not_to have_key('max_stack_depth')
        expect(config).not_to have_key('max_standby_archive_delay')
        expect(config).not_to have_key('max_standby_streaming_delay')
        expect(config).not_to have_key('max_wal_senders')
        expect(config).not_to have_key('max_worker_processes')
        expect(config).not_to have_key('pg_partman_bgw_interval')
        expect(config).not_to have_key('pg_partman_bgw_role')
        expect(config).not_to have_key('pg_stat_statements_track')
        expect(config).not_to have_key('shared_buffers_percentage')
        expect(config).not_to have_key('temp_file_limit')
        expect(config).not_to have_key('timezone')
        expect(config).not_to have_key('track_activity_query_size')
        expect(config).not_to have_key('track_commit_timestamp')
        expect(config).not_to have_key('track_functions')
        expect(config).not_to have_key('track_io_timing')
        expect(config).not_to have_key('wal_sender_timeout')
        expect(config).not_to have_key('wal_writer_delay')
        expect(config).not_to have_key('work_mem')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ pgbouncer: [{ 'key1' => 'val1' }], timescaledb: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_postgresql_config', 'full')
        expect(config).to have_key('pgbouncer')
        expect(config).to have_key('timescaledb')
      end
    end

    context 'optional attributes' do
      it 'includes pgbouncer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('opt', required_attrs.merge(pgbouncer: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_postgresql_config', 'opt')
        expect(config).to have_key('pgbouncer')
      end

      it 'omits pgbouncer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_postgresql_config', 'minimal')
        expect(config).not_to have_key('pgbouncer')
      end
      it 'includes timescaledb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('opt', required_attrs.merge(timescaledb: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_postgresql_config', 'opt')
        expect(config).to have_key('timescaledb')
      end

      it 'omits timescaledb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_postgresql_config', 'minimal')
        expect(config).not_to have_key('timescaledb')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_postgresql_config', 'typed')
        expect(config['cluster_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_postgresql_config('first', required_attrs)
        synth.digitalocean_database_postgresql_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_postgresql_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_postgresql_config,
    method: :digitalocean_database_postgresql_config,
    required_attrs: { cluster_id: 'test-value' },
    expected_outputs: [:id, :autovacuum_analyze_scale_factor, :autovacuum_analyze_threshold, :autovacuum_freeze_max_age, :autovacuum_max_workers, :autovacuum_naptime, :autovacuum_vacuum_cost_delay, :autovacuum_vacuum_cost_limit, :autovacuum_vacuum_scale_factor, :autovacuum_vacuum_threshold, :backup_hour, :backup_minute, :bgwriter_delay, :bgwriter_flush_after, :bgwriter_lru_maxpages, :bgwriter_lru_multiplier, :deadlock_timeout, :default_toast_compression, :idle_in_transaction_session_timeout, :jit, :log_autovacuum_min_duration, :log_error_verbosity, :log_line_prefix, :log_min_duration_statement, :max_files_per_process, :max_locks_per_transaction, :max_logical_replication_workers, :max_parallel_workers, :max_parallel_workers_per_gather, :max_pred_locks_per_transaction, :max_prepared_transactions, :max_replication_slots, :max_stack_depth, :max_standby_archive_delay, :max_standby_streaming_delay, :max_wal_senders, :max_worker_processes, :pg_partman_bgw_interval, :pg_partman_bgw_role, :pg_stat_statements_track, :shared_buffers_percentage, :temp_file_limit, :timezone, :track_activity_query_size, :track_commit_timestamp, :track_functions, :track_io_timing, :wal_sender_timeout, :wal_writer_delay, :work_mem],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
