# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_mongodb_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabaseMongodbConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value' } }

  describe ':digitalocean_database_mongodb_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_mongodb_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_mongodb_config', 'test')
        validate_required_attributes(config, [:cluster_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_mongodb_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_mongodb_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_mongodb_config('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_mongodb_config.test.id}")
        expect(ref.default_read_concern).to eq("${digitalocean_database_mongodb_config.test.default_read_concern}")
        expect(ref.default_write_concern).to eq("${digitalocean_database_mongodb_config.test.default_write_concern}")
        expect(ref.slow_op_threshold_ms).to eq("${digitalocean_database_mongodb_config.test.slow_op_threshold_ms}")
        expect(ref.transaction_lifetime_limit_seconds).to eq("${digitalocean_database_mongodb_config.test.transaction_lifetime_limit_seconds}")
        expect(ref.verbosity).to eq("${digitalocean_database_mongodb_config.test.verbosity}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_mongodb_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_mongodb_config', 'test')
        expect(config).not_to have_key('default_read_concern')
        expect(config).not_to have_key('default_write_concern')
        expect(config).not_to have_key('slow_op_threshold_ms')
        expect(config).not_to have_key('transaction_lifetime_limit_seconds')
        expect(config).not_to have_key('verbosity')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_mongodb_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_mongodb_config', 'typed')
        expect(config['cluster_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_mongodb_config('first', required_attrs)
        synth.digitalocean_database_mongodb_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_mongodb_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_mongodb_config,
    method: :digitalocean_database_mongodb_config,
    required_attrs: { cluster_id: 'test-value' },
    expected_outputs: [:id, :default_read_concern, :default_write_concern, :slow_op_threshold_ms, :transaction_lifetime_limit_seconds, :verbosity],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
