# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_gradientai_agent_knowledge_base_attachment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanGradientaiAgentKnowledgeBaseAttachment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { agent_uuid: 'test-value', knowledge_base_uuid: 'test-value' } }

  describe ':digitalocean_gradientai_agent_knowledge_base_attachment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent_knowledge_base_attachment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_gradientai_agent_knowledge_base_attachment', 'test')
        validate_required_attributes(config, [:agent_uuid, :knowledge_base_uuid])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_agent_knowledge_base_attachment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_gradientai_agent_knowledge_base_attachment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_gradientai_agent_knowledge_base_attachment('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_gradientai_agent_knowledge_base_attachment.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent_knowledge_base_attachment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_gradientai_agent_knowledge_base_attachment', 'typed')
        expect(config['agent_uuid']).to be_a(String)
        expect(config['knowledge_base_uuid']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_gradientai_agent_knowledge_base_attachment('first', required_attrs)
        synth.digitalocean_gradientai_agent_knowledge_base_attachment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_gradientai_agent_knowledge_base_attachment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_gradientai_agent_knowledge_base_attachment,
    method: :digitalocean_gradientai_agent_knowledge_base_attachment,
    required_attrs: { agent_uuid: 'test-value', knowledge_base_uuid: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
