# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_database_logsink_opensearch resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanDatabaseLogsinkOpensearch do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cluster_id: 'test-value', endpoint: 'test-value', index_prefix: 'test-value', name: 'test-value' } }

  describe ':digitalocean_database_logsink_opensearch' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'test')
        validate_required_attributes(config, [:cluster_id, :endpoint, :index_prefix, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_logsink_opensearch('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_database_logsink_opensearch)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_database_logsink_opensearch('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_database_logsink_opensearch.test.id}")
        expect(ref.logsink_id).to eq("${digitalocean_database_logsink_opensearch.test.logsink_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'test')
        expect(config).not_to have_key('logsink_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ca_cert: 'test-value', index_days_max: 3.14, timeout_seconds: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'full')
        expect(config).to have_key('ca_cert')
        expect(config).to have_key('index_days_max')
        expect(config).to have_key('timeout_seconds')
      end
    end

    context 'optional attributes' do
      it 'includes ca_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('opt', required_attrs.merge(ca_cert: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'opt')
        expect(config).to have_key('ca_cert')
      end

      it 'omits ca_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'minimal')
        expect(config).not_to have_key('ca_cert')
      end
      it 'includes index_days_max when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('opt', required_attrs.merge(index_days_max: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'opt')
        expect(config).to have_key('index_days_max')
      end

      it 'omits index_days_max when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'minimal')
        expect(config).not_to have_key('index_days_max')
      end
      it 'includes timeout_seconds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('opt', required_attrs.merge(timeout_seconds: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'opt')
        expect(config).to have_key('timeout_seconds')
      end

      it 'omits timeout_seconds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'minimal')
        expect(config).not_to have_key('timeout_seconds')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:ca_cert]
        expect(sensitive_fields).to include(:ca_cert)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_database_logsink_opensearch', 'typed')
        expect(config['cluster_id']).to be_a(String)
        expect(config['endpoint']).to be_a(String)
        expect(config['index_prefix']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_database_logsink_opensearch('first', required_attrs)
        synth.digitalocean_database_logsink_opensearch('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_database_logsink_opensearch')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_database_logsink_opensearch,
    method: :digitalocean_database_logsink_opensearch,
    required_attrs: { cluster_id: 'test-value', endpoint: 'test-value', index_prefix: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :logsink_id],
    sensitive_fields: [:ca_cert],
    immutable_fields: [],
    boolean_fields: []
end
