# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a digitalocean_volume resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DigitaloceanVolume do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', region: 'test-value', size: 3.14 } }

  describe ':digitalocean_volume' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'digitalocean_volume', 'test')
        validate_required_attributes(config, [:name, :region, :size])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_volume('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:digitalocean_volume)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.digitalocean_volume('test', required_attrs)

        expect(ref.id).to eq("${digitalocean_volume.test.id}")
        expect(ref.droplet_ids).to eq("${digitalocean_volume.test.droplet_ids}")
        expect(ref.filesystem_label).to eq("${digitalocean_volume.test.filesystem_label}")
        expect(ref.filesystem_type).to eq("${digitalocean_volume.test.filesystem_type}")
        expect(ref.urn).to eq("${digitalocean_volume.test.urn}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_volume', 'test')
        expect(config).not_to have_key('droplet_ids')
        expect(config).not_to have_key('filesystem_label')
        expect(config).not_to have_key('filesystem_type')
        expect(config).not_to have_key('urn')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', initial_filesystem_label: 'test-value', initial_filesystem_type: 'test-value', snapshot_id: 'test-value', tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_volume', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('initial_filesystem_label')
        expect(config).to have_key('initial_filesystem_type')
        expect(config).to have_key('snapshot_id')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes initial_filesystem_label when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('opt', required_attrs.merge(initial_filesystem_label: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'opt')
        expect(config).to have_key('initial_filesystem_label')
      end

      it 'omits initial_filesystem_label when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'minimal')
        expect(config).not_to have_key('initial_filesystem_label')
      end
      it 'includes initial_filesystem_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('opt', required_attrs.merge(initial_filesystem_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'opt')
        expect(config).to have_key('initial_filesystem_type')
      end

      it 'omits initial_filesystem_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'minimal')
        expect(config).not_to have_key('initial_filesystem_type')
      end
      it 'includes snapshot_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('opt', required_attrs.merge(snapshot_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'opt')
        expect(config).to have_key('snapshot_id')
      end

      it 'omits snapshot_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'minimal')
        expect(config).not_to have_key('snapshot_id')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'digitalocean_volume', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'digitalocean_volume', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['region']).to be_a(String)
        expect(config['size']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.digitalocean_volume('first', required_attrs)
        synth.digitalocean_volume('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'digitalocean_volume')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :digitalocean_volume,
    method: :digitalocean_volume,
    required_attrs: { name: 'test-value', region: 'test-value', size: 3.14 },
    expected_outputs: [:id, :droplet_ids, :filesystem_label, :filesystem_type, :urn],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
